project_id = "setra"

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/auth/callback", "http://localhost:3000/auth/reset-password"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
