insert into public.exercises (id, owner_id, name, muscle_group, equipment) values
  ('back-squat', null, 'Back Squat', 'Quads', 'Barbell'),
  ('bench-press', null, 'Bench Press', 'Chest', 'Barbell'),
  ('rdl', null, 'Romanian Deadlift', 'Hamstrings', 'Barbell'),
  ('lat-pulldown', null, 'Lat Pulldown', 'Back', 'Cable'),
  ('bulgarian-split', null, 'Bulgarian Split Squat', 'Quads', 'Dumbbell'),
  ('db-shoulder', null, 'Dumbbell Shoulder Press', 'Shoulders', 'Dumbbell'),
  ('hip-thrust', null, 'Hip Thrust', 'Glutes', 'Barbell'),
  ('seated-row', null, 'Seated Cable Row', 'Back', 'Cable'),
  ('calf-raise', null, 'Standing Calf Raise', 'Calves', 'Machine'),
  ('plank', null, 'Plank', 'Core', 'Bodyweight'),
  ('front-squat', null, 'Front Squat', 'Quads', 'Barbell'),
  ('goblet-squat', null, 'Goblet Squat', 'Quads', 'Kettlebell'),
  ('deadlift', null, 'Conventional Deadlift', 'Hamstrings', 'Barbell'),
  ('sumo-deadlift', null, 'Sumo Deadlift', 'Glutes', 'Barbell'),
  ('leg-press', null, 'Leg Press', 'Quads', 'Machine'),
  ('leg-extension', null, 'Leg Extension', 'Quads', 'Machine'),
  ('leg-curl', null, 'Lying Leg Curl', 'Hamstrings', 'Machine'),
  ('walking-lunge', null, 'Walking Lunge', 'Glutes', 'Dumbbell'),
  ('step-up', null, 'Step Up', 'Glutes', 'Dumbbell'),
  ('kb-swing', null, 'Kettlebell Swing', 'Glutes', 'Kettlebell'),
  ('glute-bridge', null, 'Banded Glute Bridge', 'Glutes', 'Band'),
  ('incline-db-press', null, 'Incline Dumbbell Press', 'Chest', 'Dumbbell'),
  ('push-up', null, 'Push Up', 'Chest', 'Bodyweight'),
  ('overhead-press', null, 'Overhead Press', 'Shoulders', 'Barbell'),
  ('lateral-raise', null, 'Lateral Raise', 'Shoulders', 'Dumbbell'),
  ('face-pull', null, 'Face Pull', 'Shoulders', 'Cable'),
  ('pull-up', null, 'Pull Up', 'Back', 'Bodyweight'),
  ('bent-row', null, 'Bent Over Row', 'Back', 'Barbell'),
  ('single-arm-row', null, 'Single Arm Row', 'Back', 'Dumbbell'),
  ('bicep-curl', null, 'Bicep Curl', 'Biceps', 'Dumbbell'),
  ('hammer-curl', null, 'Hammer Curl', 'Biceps', 'Dumbbell'),
  ('tricep-pushdown', null, 'Tricep Pushdown', 'Triceps', 'Cable'),
  ('band-pull-apart', null, 'Band Pull Apart', 'Upper Back', 'Band'),
  ('pallof-press', null, 'Pallof Press', 'Core', 'Cable'),
  ('dead-bug', null, 'Dead Bug', 'Core', 'Bodyweight'),
  ('farmers-carry', null, 'Farmer''s Carry', 'Grip', 'Kettlebell'),
  ('db-back-squat', null, 'Dumbbell Squat', 'Quads', 'Dumbbell'),
  ('kb-front-squat', null, 'Kettlebell Front Squat', 'Quads', 'Kettlebell'),
  ('banded-squat', null, 'Banded Squat', 'Quads', 'Band'),
  ('db-rdl', null, 'Dumbbell Romanian Deadlift', 'Hamstrings', 'Dumbbell'),
  ('kb-rdl', null, 'Kettlebell Romanian Deadlift', 'Hamstrings', 'Kettlebell'),
  ('single-leg-rdl', null, 'Single Leg Romanian Deadlift', 'Hamstrings', 'Dumbbell'),
  ('banded-rdl', null, 'Banded Romanian Deadlift', 'Hamstrings', 'Band'),
  ('barbell-lunge', null, 'Barbell Reverse Lunge', 'Glutes', 'Barbell'),
  ('kb-lunge', null, 'Kettlebell Reverse Lunge', 'Glutes', 'Kettlebell'),
  ('banded-lunge', null, 'Banded Lateral Lunge', 'Glutes', 'Band'),
  ('db-bench', null, 'Dumbbell Bench Press', 'Chest', 'Dumbbell'),
  ('kb-floor-press', null, 'Kettlebell Floor Press', 'Chest', 'Kettlebell'),
  ('banded-chest-press', null, 'Banded Chest Press', 'Chest', 'Band'),
  ('db-row', null, 'Dumbbell Bent Over Row', 'Back', 'Dumbbell'),
  ('kb-row', null, 'Kettlebell Row', 'Back', 'Kettlebell'),
  ('banded-row', null, 'Banded Seated Row', 'Back', 'Band'),
  ('kb-shoulder-press', null, 'Kettlebell Shoulder Press', 'Shoulders', 'Kettlebell'),
  ('banded-shoulder-press', null, 'Banded Shoulder Press', 'Shoulders', 'Band'),
  ('barbell-hip-thrust', null, 'Barbell Hip Thrust', 'Glutes', 'Barbell'),
  ('db-hip-thrust', null, 'Dumbbell Hip Thrust', 'Glutes', 'Dumbbell'),
  ('banded-hip-thrust', null, 'Banded Hip Thrust', 'Glutes', 'Band'),
  ('barbell-calf-raise', null, 'Barbell Calf Raise', 'Calves', 'Barbell'),
  ('db-calf-raise', null, 'Dumbbell Calf Raise', 'Calves', 'Dumbbell'),
  ('kb-calf-raise', null, 'Kettlebell Calf Raise', 'Calves', 'Kettlebell'),
  ('narrow-grip-pull-up', null, 'Narrow Grip Pull Up', 'Back', 'Bodyweight'),
  ('wide-grip-pull-up', null, 'Wide Grip Pull Up', 'Back', 'Bodyweight'),
  ('neutral-grip-pull-up', null, 'Neutral Grip Pull Up', 'Back', 'Bodyweight'),
  ('assisted-pull-up', null, 'Assisted Pull Up', 'Back', 'Machine'),
  ('band-assisted-pull-up', null, 'Band Assisted Pull Up', 'Back', 'Band'),
  ('weighted-pull-up', null, 'Weighted Pull Up', 'Back', 'Bodyweight'),
  ('chin-up', null, 'Chin Up', 'Back', 'Bodyweight'),
  ('narrow-grip-chin-up', null, 'Narrow Grip Chin Up', 'Back', 'Bodyweight'),
  ('machine-pull-up', null, 'Machine Pull Up', 'Back', 'Machine'),
  ('barbell-rdl', null, 'Barbell Romanian Deadlift', 'Hamstrings', 'Barbell'),
  ('single-leg-barbell-rdl', null, 'Single Leg Barbell Romanian Deadlift', 'Hamstrings', 'Barbell'),
  ('single-leg-db-rdl', null, 'Single Leg Dumbbell Romanian Deadlift', 'Hamstrings', 'Dumbbell'),
  ('single-leg-kb-rdl', null, 'Single Leg Kettlebell Romanian Deadlift', 'Hamstrings', 'Kettlebell'),
  ('b-stance-barbell-rdl', null, 'B-Stance Barbell Romanian Deadlift', 'Hamstrings', 'Barbell'),
  ('b-stance-db-rdl', null, 'B-Stance Dumbbell Romanian Deadlift', 'Hamstrings', 'Dumbbell'),
  ('smith-machine-rdl', null, 'Smith Machine Romanian Deadlift', 'Hamstrings', 'Machine'),
  ('landmine-rdl', null, 'Landmine Romanian Deadlift', 'Hamstrings', 'Barbell'),
  ('cable-rdl', null, 'Cable Romanian Deadlift', 'Hamstrings', 'Cable'),
  ('stiff-leg-deadlift', null, 'Stiff Leg Barbell Deadlift', 'Hamstrings', 'Barbell'),
  ('trap-bar-deadlift', null, 'Trap Bar Deadlift', 'Hamstrings', 'Trap Bar'),
  ('hack-squat', null, 'Hack Squat', 'Quads', 'Machine'),
  ('smith-back-squat', null, 'Smith Machine Back Squat', 'Quads', 'Machine'),
  ('heels-elevated-squat', null, 'Heels Elevated Dumbbell Squat', 'Quads', 'Dumbbell'),
  ('single-leg-press', null, 'Single Leg Press', 'Quads', 'Machine'),
  ('barbell-bulgarian-split', null, 'Barbell Bulgarian Split Squat', 'Quads', 'Barbell'),
  ('smith-bulgarian-split', null, 'Smith Machine Bulgarian Split Squat', 'Quads', 'Machine'),
  ('cable-pull-through', null, 'Cable Pull Through', 'Glutes', 'Cable'),
  ('single-leg-hip-thrust', null, 'Single Leg Hip Thrust', 'Glutes', 'Bodyweight'),
  ('smith-hip-thrust', null, 'Smith Machine Hip Thrust', 'Glutes', 'Machine'),
  ('machine-hip-thrust', null, 'Machine Hip Thrust', 'Glutes', 'Machine'),
  ('cable-kickback', null, 'Cable Glute Kickback', 'Glutes', 'Cable'),
  ('machine-chest-press', null, 'Machine Chest Press', 'Chest', 'Machine'),
  ('incline-barbell-press', null, 'Incline Barbell Bench Press', 'Chest', 'Barbell'),
  ('incline-machine-press', null, 'Incline Machine Chest Press', 'Chest', 'Machine'),
  ('cable-chest-fly', null, 'Cable Chest Fly', 'Chest', 'Cable'),
  ('chest-supported-row', null, 'Chest Supported Dumbbell Row', 'Back', 'Dumbbell'),
  ('machine-row', null, 'Machine Seated Row', 'Back', 'Machine'),
  ('t-bar-row', null, 'T-Bar Row', 'Back', 'Machine'),
  ('wide-grip-lat-pulldown', null, 'Wide Grip Lat Pulldown', 'Back', 'Cable'),
  ('narrow-grip-lat-pulldown', null, 'Narrow Grip Lat Pulldown', 'Back', 'Cable'),
  ('single-arm-lat-pulldown', null, 'Single Arm Lat Pulldown', 'Back', 'Cable'),
  ('arnold-press', null, 'Arnold Press', 'Shoulders', 'Dumbbell'),
  ('machine-shoulder-press', null, 'Machine Shoulder Press', 'Shoulders', 'Machine'),
  ('cable-lateral-raise', null, 'Cable Lateral Raise', 'Shoulders', 'Cable'),
  ('rear-delt-fly', null, 'Rear Delt Fly', 'Shoulders', 'Machine'),
  ('ez-bar-curl', null, 'EZ Bar Bicep Curl', 'Biceps', 'EZ Bar'),
  ('cable-bicep-curl', null, 'Cable Bicep Curl', 'Biceps', 'Cable'),
  ('overhead-tricep-extension', null, 'Overhead Tricep Extension', 'Triceps', 'Cable'),
  ('skull-crusher', null, 'EZ Bar Skull Crusher', 'Triceps', 'EZ Bar'),
  ('machine-hip-abduction', null, 'Machine Hip Abduction', 'Glutes', 'Machine'),
  ('machine-hip-adduction', null, 'Machine Hip Adduction', 'Adductors', 'Machine'),
  ('cable-crunches', null, 'Cable Crunches', 'Core', 'Cable'),
  ('leg-raises', null, 'Leg Raises', 'Core', 'Bodyweight'),
  ('lying-leg-raise', null, 'Lying Leg Raise', 'Core', 'Bodyweight'),
  ('hanging-leg-raise', null, 'Hanging Leg Raise', 'Core', 'Bodyweight'),
  ('captains-chair-leg-raise', null, 'Captain''s Chair Leg Raise', 'Core', 'Machine'),
  ('single-leg-squat', null, 'Single Leg Squat', 'Quads', 'Bodyweight'),
  ('single-leg-squat-to-box', null, 'Single Leg Squat to Box', 'Quads', 'Bodyweight'),
  ('single-leg-squat-off-box', null, 'Single Leg Squat off Box', 'Quads', 'Bodyweight'),
  ('pistol-squat', null, 'Pistol Squat', 'Quads', 'Bodyweight'),
  ('assisted-pistol-squat', null, 'Assisted Pistol Squat', 'Quads', 'Bodyweight'),
  ('trx-single-leg-squat', null, 'TRX Single Leg Squat', 'Quads', 'Suspension Trainer'),
  ('dumbbell-single-leg-squat', null, 'Dumbbell Single Leg Squat', 'Quads', 'Dumbbell'),
  ('kettlebell-single-leg-squat', null, 'Kettlebell Single Leg Squat', 'Quads', 'Kettlebell'),
  ('skater-squat', null, 'Skater Squat', 'Quads', 'Bodyweight')
on conflict (id) do update set
  name = excluded.name,
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  updated_at = now();
