"use client";
/* eslint-disable jsx-a11y/label-has-associated-control -- controls use explicit htmlFor/id pairs inside compact setting rows */

import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import {useAuth} from "@/components/auth/auth-provider";
import {DiaryService} from "@/lib/data/diary-service";
import {TrainingSessionService} from "@/lib/data/training-session-service";
import {FriendsService} from "@/lib/social/friends-service";
import type {FriendPrivacy,FriendProfile,SharedItem,SocialConnection,SocialNotification,SocialProfile} from "@/lib/social/types";
import {SharedItemPreview} from "@/components/social/shared-item-preview";
import type {EnduranceTemplate,Template} from "@/lib/setra/types";
import {createRecordId} from "@/lib/setra/new-workout";
import {createSetraTheme,useResolvedAppearance} from "@/lib/setra/appearance";
import {formatLoad,type StrengthUnit} from "@/lib/setra/units";
import "./friends.css";
import "./friends-comparison.css";

type Tab="friends"|"requests"|"find"|"shared";
const defaultPrivacy:FriendPrivacy={sharePbs:false,shareCompletedWorkouts:false,shareTrainingSummary:false};
const dateLabel=(value:string)=>new Intl.DateTimeFormat("en-AU",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value));
const durationLabel=(seconds:number)=>{const hours=Math.floor(seconds/3600);const minutes=Math.floor(seconds%3600/60);const remainder=Math.round(seconds%60);return hours?`${hours}:${String(minutes).padStart(2,"0")}:${String(remainder).padStart(2,"0")}`:`${minutes}:${String(remainder).padStart(2,"0")}`};

export default function FriendsPage(){
  const {user}=useAuth();const service=useMemo(()=>user?new FriendsService(user.id):null,[user]);
  const [tab,setTab]=useState<Tab>("friends");const [connections,setConnections]=useState<SocialConnection[]>([]);const [shared,setShared]=useState<SharedItem[]>([]);const [privacy,setPrivacy]=useState(defaultPrivacy);const [username,setUsername]=useState("");const [savedUsername,setSavedUsername]=useState("");
  const [query,setQuery]=useState("");const [results,setResults]=useState<SocialProfile[]>([]);const [profile,setProfile]=useState<FriendProfile|null>(null);const [preview,setPreview]=useState<SharedItem|null>(null);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
  const [notifications,setNotifications]=useState<SocialNotification[]>([]);
  const [accent,setAccent]=useState("#409ECE");const [appearance,setAppearance]=useState<"light"|"dark"|"system">("system");const [textScale,setTextScale]=useState<1|1.1|1.2|1.3>(1);const resolved=useResolvedAppearance(appearance);
  const [unit,setUnit]=useState<StrengthUnit>("kg");const [ownStrengthPbs,setOwnStrengthPbs]=useState<Map<string,number>>(new Map());const [ownEndurancePbs,setOwnEndurancePbs]=useState<Map<number,number>>(new Map());
  const refresh=useCallback(async()=>{if(!service||!user)return;setLoading(true);try{const diary=new DiaryService(user.id);const endurance=new TrainingSessionService(user.id);const [identity,permissions,people,items,profileSettings,training,enduranceSessions]=await Promise.all([service.loadIdentity(),service.loadPrivacy(),service.connections(),service.sharedWithMe(),diary.loadProfile(),diary.load(),endurance.loadEndurance()]);setUsername(identity.username);setSavedUsername(identity.username);setPrivacy(permissions);setConnections(people);setShared(items);setAccent(profileSettings.appColour);setAppearance(profileSettings.appearanceMode);setTextScale(profileSettings.textScale);setUnit(profileSettings.preferredUnit);const strengthPbs=new Map<string,number>();for(const workout of training.workouts)for(const exercise of workout.exercises)if(!exercise.skipped)for(const set of exercise.sets)if(set.done&&Number(set.weight)>0)strengthPbs.set(exercise.exerciseId,Math.max(strengthPbs.get(exercise.exerciseId)||0,Number(set.weight)));setOwnStrengthPbs(strengthPbs);const endurancePbs=new Map<number,number>();for(const session of enduranceSessions)if(session.status==="completed"&&session.distanceKm&&session.durationMinutes){const metres=Math.round(session.distanceKm*1000);const standard=[5000,10000,21098].find(value=>Math.abs(value-metres)<=1);if(standard)endurancePbs.set(standard,Math.min(endurancePbs.get(standard)||Infinity,session.durationMinutes*60))}setOwnEndurancePbs(endurancePbs);void service.markNotificationsRead()}catch(error){setMessage(error instanceof Error?error.message:"Friends could not be loaded. Apply the Friends migration first.")}finally{setLoading(false)}},[service,user]);
  useEffect(()=>{void refresh()},[refresh]);
  useEffect(()=>{if(!service)return;service.notifications().then(items=>{setNotifications(items);return service.markNotificationsRead()}).catch(()=>{})},[service]);
  const friends=connections.filter(item=>item.status==="accepted");const incoming=connections.filter(item=>item.status==="pending"&&item.direction==="incoming");const outgoing=connections.filter(item=>item.status==="pending"&&item.direction==="outgoing");const blocked=connections.filter(item=>item.status==="blocked");
  async function action(work:()=>Promise<unknown>,success:string){setMessage("");try{await work();setMessage(success);await refresh()}catch(error){setMessage(error instanceof Error?error.message:"That action could not be completed.")}}
  async function search(){if(!service||query.trim().length<2)return;setMessage("");try{setResults(await service.search(query))}catch(error){setMessage(error instanceof Error?error.message:"Search is unavailable.")}}
  async function saveSocialSettings(){if(!service)return;setMessage("");try{if(username!==savedUsername){const value=await service.saveIdentity(username);setUsername(value);setSavedUsername(value)}await service.savePrivacy(privacy);setMessage("Friends settings saved.")}catch(error){setMessage(error instanceof Error?error.message:"Settings could not be saved.")}}
  async function openProfile(friend:SocialConnection){if(!service)return;try{setProfile(await service.friendProfile(friend.otherUserId))}catch(error){setMessage(error instanceof Error?error.message:"Friend profile is unavailable.")}}
  async function saveTemplate(item:SharedItem){if(!user||!service)return;try{if(item.itemType==="strength_template"){
      const raw=item.snapshot as Record<string,unknown>;const diary=new DiaryService(user.id);const current=await diary.load();const byId=new Map(current.exercises.map(exercise=>[exercise.id,exercise.id]));const byName=new Map(current.exercises.map(exercise=>[exercise.name.trim().toLowerCase(),exercise.id]));const exercises=(Array.isArray(raw.exercises)?raw.exercises:[]).filter((value):value is Record<string,unknown>=>Boolean(value)&&typeof value==="object").map(value=>({...value,resolvedExerciseId:byId.get(String(value.exerciseId))||byName.get(String(value.exerciseName||"").trim().toLowerCase())} as Record<string,unknown>)).filter(value=>Boolean(value.resolvedExerciseId)).map(value=>({exerciseId:String(value.resolvedExerciseId),sets:Number(value.sets)||3,reps:String(value.reps||"8"),group:value.group?String(value.group):undefined,plannedLoad:value.plannedLoad as Template["exercises"][number]["plannedLoad"]}));
      if(!exercises.length)throw new Error("None of the exercises in this template are available in your catalogue.");const copy:Template={id:createRecordId("shared-template"),name:String(raw.name||item.title),focus:String(raw.focus||""),warmup:Array.isArray(raw.warmup)?raw.warmup as Template["warmup"]:[],exercises,supersetNames:typeof raw.supersetNames==="object"?raw.supersetNames as Record<string,string>:undefined};await diary.saveTemplate(copy);
    }else if(item.itemType==="endurance_template"){
      const raw=item.snapshot as unknown as EnduranceTemplate;const copy:EnduranceTemplate={...raw,id:createRecordId("shared-endurance-template"),title:raw.title||item.title,notes:"",blocks:Array.isArray(raw.blocks)?raw.blocks.map(block=>({...block,id:createRecordId("shared-step")})):[]};await new TrainingSessionService(user.id).saveTemplate(copy);
    }else return;await service.updateSharedItem(item.id,"saved");setMessage("Saved as your own independent template.");await refresh()}catch(error){setMessage(error instanceof Error?error.message:"The template could not be saved.")}}
  const theme=createSetraTheme(accent,resolved,textScale);
  return <main className="friends-screen" style={theme} data-theme={resolved}>
    <header className="friends-header"><Link href="/profile" aria-label="Back to profile">‹</Link><div><small>TRUSTED CONNECTIONS</small><b>Friends</b></div><span/></header>
    <div className="friends-content">
      <section className="friends-intro"><span>SETRA FRIENDS</span><h1>Train connected.</h1><p>Share only what you choose, with people you approve.</p></section>
      <nav className="friends-tabs" aria-label="Friends sections">{([['friends','Friends'],['requests',`Requests${incoming.length?` ${incoming.length}`:""}`],['find','Add Friend'],['shared',`Shared${shared.filter(item=>item.recipientStatus==="new").length?` ${shared.filter(item=>item.recipientStatus==="new").length}`:""}`]] as [Tab,string][]).map(([value,label])=><button key={value} className={tab===value?"active":""} onClick={()=>setTab(value)}>{label}</button>)}</nav>
      {notifications.some(item=>!item.readAt)&&<div className="social-notifications">{notifications.filter(item=>!item.readAt).slice(0,3).map(item=><button key={item.notificationId} onClick={()=>setTab(item.notificationType.includes("shared")?"shared":"requests")}><b>{item.notificationType==="friend_request"?"Friend request":item.notificationType==="friend_accepted"?"Request accepted":item.notificationType==="template_shared"?"Template shared":"Workout shared"}</b><span>{item.actorDisplayName}</span></button>)}</div>}
      {message&&<p className="friends-message" role="status">{message}</p>}
      {loading?<p className="friends-empty">Loading your connections…</p>:<>
        {tab==="friends"&&<section className="friends-panel"><header><span>YOUR FRIENDS</span><h2>{friends.length} {friends.length===1?"connection":"connections"}</h2></header>{friends.length?<div className="friends-list">{friends.map(friend=><article key={friend.connectionId}><button className="friend-main" onClick={()=>openProfile(friend)}><i>{friend.displayName.slice(0,1).toUpperCase()}</i><span><b>{friend.displayName}</b><small>@{friend.username}</small></span><em>›</em></button><div><button onClick={()=>action(()=>service!.remove(friend.connectionId),"Friend removed.")}>Remove</button><button onClick={()=>action(()=>service!.block(friend.otherUserId),"Account blocked.")}>Block</button></div></article>)}</div>:<p className="friends-empty">No friends yet. Find someone by their Setra username.</p>}
          <div className="blocked-list">{blocked.map(item=><button key={item.connectionId} onClick={()=>action(()=>service!.unblock(item.connectionId),"Account unblocked.")}>Unblock @{item.username}</button>)}</div></section>}
        {tab==="requests"&&<section className="friends-panel"><header><span>REQUESTS</span><h2>Connection requests</h2></header>{!incoming.length&&!outgoing.length?<p className="friends-empty">No pending requests.</p>:<div className="request-list">{incoming.map(item=><article key={item.connectionId}><div><b>{item.displayName}</b><small>@{item.username} wants to connect</small></div><span><button onClick={()=>action(()=>service!.respond(item.connectionId,false),"Request declined.")}>Decline</button><button className="primary" onClick={()=>action(()=>service!.respond(item.connectionId,true),"Friend added.")}>Accept</button></span></article>)}{outgoing.map(item=><article key={item.connectionId}><div><b>{item.displayName}</b><small>Request sent to @{item.username}</small></div><span><button onClick={()=>action(()=>service!.cancel(item.connectionId),"Request cancelled.")}>Cancel</button></span></article>)}</div>}</section>}
        {tab==="find"&&<><section className="friends-panel"><header><span>FIND PEOPLE</span><h2>Search by username</h2><p>Email addresses and training data are never shown.</p></header><div className="friend-search"><input value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==="Enter")void search()}} placeholder="@username"/><button onClick={search}>Search</button></div><div className="search-results">{results.map(item=><article key={item.userId}><i>{item.displayName.slice(0,1).toUpperCase()}</i><span><b>{item.displayName}</b><small>@{item.username}</small></span><button disabled={Boolean(item.connectionStatus)} onClick={()=>action(()=>service!.sendRequest(item.userId),"Friend request sent.")}>{item.connectionStatus||"Add"}</button></article>)}</div></section>
          <section className="friends-panel social-settings"><header><span>YOUR SOCIAL ID</span><h2>Username and privacy</h2><p>Sharing stays off until you choose otherwise. Directly shared items remain available to their recipient.</p></header><label>USERNAME<div><span>@</span><input value={username} maxLength={30} onChange={event=>setUsername(event.target.value.toLowerCase().replace(/[^a-z0-9_]/g,""))} placeholder="your_username"/></div></label><label className="privacy-toggle" htmlFor="share-pbs"><span><b>Share PBs</b><small>Accepted friends may view and compare your PBs.</small></span><input id="share-pbs" type="checkbox" checked={privacy.sharePbs} onChange={event=>setPrivacy({...privacy,sharePbs:event.target.checked})}/></label><label className="privacy-toggle" htmlFor="share-workouts"><span><b>Share completed workouts</b><small>Allows a compact friend view, never private notes.</small></span><input id="share-workouts" type="checkbox" checked={privacy.shareCompletedWorkouts} onChange={event=>setPrivacy({...privacy,shareCompletedWorkouts:event.target.checked})}/></label><label className="privacy-toggle" htmlFor="share-summary"><span><b>Share training summary</b><small>Shows compact seven-day totals only.</small></span><input id="share-summary" type="checkbox" checked={privacy.shareTrainingSummary} onChange={event=>setPrivacy({...privacy,shareTrainingSummary:event.target.checked})}/></label><button className="settings-save" onClick={saveSocialSettings}>Save Friends settings</button></section></>}
        {tab==="shared"&&<section className="friends-panel"><header><span>SHARED WITH ME</span><h2>Workouts and templates</h2></header>{shared.length?<div className="shared-list">{shared.map(item=>{const sender=friends.find(friend=>friend.otherUserId===item.senderUserId);const isTemplate=item.itemType.endsWith("template");return <article key={item.id}><div><small>{item.itemType.replaceAll("_"," ").toUpperCase()}</small><b>{item.title}</b><span>{sender?.displayName||"Setra friend"} · {dateLabel(item.createdAt)}</span></div><footer><button onClick={()=>{setPreview(item);void service!.updateSharedItem(item.id,"viewed")}}>Preview</button>{isTemplate&&item.recipientStatus!=="saved"&&<button className="primary" onClick={()=>saveTemplate(item)}>Save to My Templates</button>}<button onClick={()=>action(()=>service!.updateSharedItem(item.id,"dismissed"),"Shared item dismissed.")}>Dismiss</button></footer></article>})}</div>:<p className="friends-empty">Workouts and templates shared with you will appear here.</p>}</section>}
      </>}
    </div>
    {profile&&<div className="friends-profile-overlay" onMouseDown={event=>{if(event.target===event.currentTarget)setProfile(null)}}><section className="friend-profile" role="dialog" aria-modal="true" aria-labelledby="friend-profile-title"><header><div><small>FRIEND PROFILE</small><h2 id="friend-profile-title">{profile.displayName}</h2><p>@{profile.username}</p></div><button onClick={()=>setProfile(null)} aria-label="Close">×</button></header>{profile.permissions.trainingSummary&&<div className="friend-summary"><span><b>{profile.trainingSummary.strengthSessions||0}</b><small>Strength this week</small></span><span><b>{profile.trainingSummary.enduranceSessions||0}</b><small>Endurance this week</small></span><span><b>{Math.round(profile.trainingSummary.trainingMinutes||0)}</b><small>Minutes</small></span></div>}<section><span>PB COMPARISON</span>{profile.permissions.pbs?<div className="friend-pbs">{profile.strengthPbs.map(pb=><div key={pb.exercise_id}><b>{pb.exercise_name}</b><span><small>You</small><strong>{ownStrengthPbs.has(pb.exercise_id)?formatLoad(String(ownStrengthPbs.get(pb.exercise_id)),unit):"–"}</strong></span><span><small>{profile.displayName}</small><strong>{formatLoad(String(pb.weight),unit)}</strong></span></div>)}{profile.endurancePbs.map(pb=><div key={`${pb.activity_type}-${pb.distance_metres}`}><b>{pb.distance_metres===21098?"Half marathon":`${pb.distance_metres/1000}K`} · {pb.activity_type}</b><span><small>You</small><strong>{ownEndurancePbs.has(pb.distance_metres)?durationLabel(ownEndurancePbs.get(pb.distance_metres)!):"–"}</strong></span><span><small>{profile.displayName}</small><strong>{durationLabel(pb.duration_seconds)}</strong></span></div>)}{!profile.strengthPbs.length&&!profile.endurancePbs.length&&<p>No comparable PBs yet.</p>}</div>:<p>PB sharing is private for this friend.</p>}</section>{profile.permissions.completedWorkouts&&<section className="friend-recent"><span>RECENT TRAINING</span>{profile.recentWorkouts.map(item=><div key={`${item.type}-${item.date}-${item.title}`}><b>{item.title}</b><small>{dateLabel(item.date)} · {item.type}</small></div>)}</section>}</section></div>}
    {preview&&<div className="friends-profile-overlay" onMouseDown={event=>{if(event.target===event.currentTarget)setPreview(null)}}><section className="friend-profile shared-preview" role="dialog" aria-modal="true" aria-labelledby="shared-preview-title"><header><div><small>{preview.itemType.replaceAll("_"," ").toUpperCase()}</small><h2 id="shared-preview-title">{preview.title}</h2><p>Shared {dateLabel(preview.createdAt)}</p></div><button onClick={()=>setPreview(null)} aria-label="Close">×</button></header><SharedItemPreview item={preview} unit={unit}/></section></div>}
  </main>;
}
