"use client";

import Link from "next/link";
import {useRouter} from "next/navigation";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {useAuth} from "@/components/auth/auth-provider";
import {loadLocalAppearance,loadLocalAppColour,loadLocalTextScale,loadPendingDiaryChanges,saveLocalAppearance,saveLocalAppColour,saveLocalTextScale} from "@/lib/data/local-diary";
import {ProfileService,type ProfileSettings} from "@/lib/profile/profile-service";
import {usePremiumAccess} from "@/lib/premium/use-premium-access";
import {contrastColour,createSetraTheme,useResolvedAppearance,type TextScale} from "@/lib/setra/appearance";
import {weekdayOptions} from "@/lib/setra/week";
import {withTimeout} from "@/lib/async/with-timeout";
import "./profile.css";

const colours=[{name:"Blue",value:"#409ECE"},{name:"Coral",value:"#FF6B6B"},{name:"Yellow",value:"#F6C445"},{name:"Green",value:"#55B96D"},{name:"Purple",value:"#8B72D9"},{name:"Grey",value:"#6B7280"}];
const defaults:ProfileSettings={displayName:"",fullName:"",dateOfBirth:"",preferredUnit:"kg",trainingGoal:"",experienceLevel:"",trainingPreference:"strength",appColour:"#409ECE",appearanceMode:"system",textScale:1,showWorkoutTimingPopup:true,showPbPopup:true,weekStartsOn:1,lastWeeklyPreviewWeekStart:null,weeklySessionGoal:null,awardsTimezone:""};
const initials=(name:string,email?:string)=>{const words=name.trim().split(/\s+/).filter(Boolean);return (words.length?words.map(word=>word[0]).join("").slice(0,3):(email?.[0]||"S")).toUpperCase()};

export default function ProfilePage(){
  const {user,signOut}=useAuth();
  const userId=user?.id;const metadataDisplayName=typeof user?.user_metadata?.display_name==="string"?user.user_metadata.display_name:"";
  const router=useRouter();
  const {subscription}=usePremiumAccess();
  const service=useMemo(()=>user?new ProfileService(user.id):null,[user]);
  const [settings,setSettings]=useState<ProfileSettings>(defaults);
  const [saved,setSaved]=useState<ProfileSettings>(defaults);
  const [loading,setLoading]=useState(true);
  const [saving,setSaving]=useState(false);
  const [accountBusy,setAccountBusy]=useState(false);
  const [message,setMessage]=useState("");
  const [loadError,setLoadError]=useState(false);
  const [pendingExportChanges,setPendingExportChanges]=useState(0);
  const [exportState,setExportState]=useState<"idle"|"preparing"|"downloading"|"success"|"partial"|"error"|"cancelled">("idle");
  const loadGeneration=useRef(0);const loadedAccount=useRef<string|null>(null);const dirtyRef=useRef(false);
  const resolvedAppearance=useResolvedAppearance(settings.appearanceMode);

  const loadProfile=useCallback(async()=>{if(!service||!userId)return;const generation=++loadGeneration.current;if(loadedAccount.current!==userId){loadedAccount.current=userId;dirtyRef.current=false;setSettings(defaults);setSaved(defaults)}setLoading(true);setLoadError(false);setMessage("");const cached=loadLocalAppColour(userId);const cachedAppearance=loadLocalAppearance(userId);const cachedTextScale=loadLocalTextScale(userId);if(!dirtyRef.current&&(cached||cachedAppearance||cachedTextScale))setSettings(current=>({...current,...(cached?{appColour:cached}:{}),...(cachedAppearance?{appearanceMode:cachedAppearance}:{}),...(cachedTextScale?{textScale:cachedTextScale}:{})}));try{const profile=await withTimeout(service.load(),15000,"Profile loading took too long. Your entered settings are still here; check your connection and retry.");if(generation!==loadGeneration.current||loadedAccount.current!==userId)return;const next={...profile,displayName:profile.displayName||metadataDisplayName};setSaved(next);if(!dirtyRef.current)setSettings(next);saveLocalTextScale(next.textScale,userId)}catch(error){if(generation===loadGeneration.current){setLoadError(true);setMessage(error instanceof Error?error.message:"Profile settings could not be loaded.")}}finally{if(generation===loadGeneration.current)setLoading(false)}},[metadataDisplayName,service,userId]);
  useEffect(()=>{void loadProfile()},[loadProfile]);
  useEffect(()=>{setPendingExportChanges(loadPendingDiaryChanges(user?.id).length)},[user?.id]);
  const dirty=JSON.stringify(settings)!==JSON.stringify(saved);
  useEffect(()=>{dirtyRef.current=dirty},[dirty]);
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(!dirty)return;event.preventDefault();event.returnValue=""};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
  useEffect(()=>{const guardBack=()=>{if(!dirtyRef.current)return;if(window.confirm("Leave without saving your profile changes?")){dirtyRef.current=false;return}window.history.go(1)};window.addEventListener("popstate",guardBack);return()=>window.removeEventListener("popstate",guardBack)},[]);
  async function save(){if(!service||saving)return;setSaving(true);setMessage("");try{await withTimeout(service.save(settings),15000,"Saving took too long. Your changes remain on this screen; please retry.");saveLocalAppColour(settings.appColour,user?.id);saveLocalAppearance(settings.appearanceMode,user?.id);saveLocalTextScale(settings.textScale,user?.id);setSaved(settings);router.replace("/")}catch(error){setMessage(error instanceof Error?error.message:"Settings could not be saved. Your changes remain on this screen.")}finally{setSaving(false)}}
  async function downloadExport(){
    if(exportState==="preparing"||exportState==="downloading")return;setExportState("preparing");setMessage("Preparing your cloud export…");
    const controller=new AbortController();const timeout=window.setTimeout(()=>controller.abort(),60_000);let objectUrl:string|undefined;
    try{
      const response=await fetch("/api/account/export",{cache:"no-store",signal:controller.signal});if(!response.ok)throw new Error("The export could not be prepared.");
      setExportState("downloading");setMessage("Checking the completed export…");const blob=await response.blob();const result=JSON.parse(await blob.text()) as {complete:boolean;errors?:{section:string;message:string}[]};
      const partial=!result.complete;const filename=`setra-data-${new Date().toISOString().slice(0,10)}${partial?"-partial":""}.json`;objectUrl=URL.createObjectURL(blob);const link=document.createElement("a");link.href=objectUrl;link.download=filename;document.body.appendChild(link);link.click();link.remove();
      if(partial){setExportState("partial");setMessage(`A partial export was downloaded. Missing sections: ${(result.errors||[]).map(item=>item.section).join(", ")||"unknown"}. Retry when your connection is stable.`)}else{setExportState("success");setMessage("Your complete cloud export has been downloaded.")}
    }catch(error){if(error instanceof DOMException&&error.name==="AbortError"){setExportState("cancelled");setMessage("The export timed out before it was complete. Nothing was reported as successfully downloaded—please retry.")}else{setExportState("error");setMessage(error instanceof Error?error.message:"Export could not be prepared.")}}
    finally{window.clearTimeout(timeout);if(objectUrl)window.setTimeout(()=>URL.revokeObjectURL(objectUrl!),0)}
  }
  const guardNavigation=(event:React.MouseEvent<HTMLAnchorElement>)=>{if(dirty&&!window.confirm("Leave without saving your profile changes?"))event.preventDefault()};
  const guardedSignOut=()=>{if(dirty&&!window.confirm("Sign out without saving your profile changes?"))return;void signOut()};
  async function requestDeletion(){if(accountBusy||!window.confirm("Request deletion of your Setra account and training data? This records a request for review; it does not delete anything immediately."))return;setAccountBusy(true);setMessage("");try{const response=await fetch("/api/account/deletion-request",{method:"POST"});const result=await response.json();if(!response.ok)throw new Error(result.error||"The request could not be recorded.");setMessage("Deletion request recorded. Your account remains active until the request is completed.")}catch(error){setMessage(error instanceof Error?error.message:"The request could not be recorded.")}finally{setAccountBusy(false)}}
  const contrast=contrastColour(settings.appColour);
  const theme=createSetraTheme(settings.appColour,resolvedAppearance,settings.textScale);

  return <main className="profile-screen" style={theme} data-light-accent={contrast==="#0F172A"} data-theme={resolvedAppearance}>
    <header className="profile-header"><Link href="/" aria-label="Back to Setra" onClick={guardNavigation}><span aria-hidden="true">‹</span></Link><b>Profile</b><span/></header>
    <div className="profile-content">
      <section className="profile-identity"><span>{initials(settings.displayName,user?.email)}</span><div><small>{subscription.tier==="premium"?"SETRA PREMIUM":"SETRA ATHLETE"}</small><h1>{settings.displayName||"Your profile"}</h1><p>{user?.email}</p></div></section>

      <Link className="profile-awards-link" href="/awards" onClick={guardNavigation}><span>AWARDS &amp; STREAKS</span><div><i>◆</i><p><b>Your training record</b><small>Consistency, milestones and the work adding up.</small></p><em>›</em></div></Link>

      <section className="profile-section"><header><span>YOUR DETAILS</span><h2>Account details</h2></header><label className="profile-field">NAME<input disabled={loading} maxLength={120} value={settings.fullName} onChange={event=>setSettings({...settings,fullName:event.target.value})} placeholder="Your full name"/></label><label className="profile-field">DISPLAY NAME<input disabled={loading} maxLength={60} value={settings.displayName} onChange={event=>setSettings({...settings,displayName:event.target.value})} placeholder="Shown throughout Setra"/></label><label className="profile-field">DATE OF BIRTH<input type="date" disabled={loading} value={settings.dateOfBirth} onChange={event=>setSettings({...settings,dateOfBirth:event.target.value})}/></label><label className="profile-field">EMAIL<input value={user?.email||""} disabled/></label><div className="profile-field-grid"><label className="profile-field">PREFERRED UNIT<select value={settings.preferredUnit} onChange={event=>setSettings({...settings,preferredUnit:event.target.value as "kg"|"lb"})}><option value="kg">Kilograms (kg)</option><option value="lb">Pounds (lb)</option></select></label><label className="profile-field">EXPERIENCE<select value={settings.experienceLevel} onChange={event=>setSettings({...settings,experienceLevel:event.target.value as ProfileSettings["experienceLevel"]})}><option value="">Not selected</option><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label></div><label className="profile-field">TRAINING GOAL<textarea maxLength={240} value={settings.trainingGoal} onChange={event=>setSettings({...settings,trainingGoal:event.target.value})} placeholder="What are you currently training towards?"/></label></section>

      <section className="profile-section"><header><span>APPEARANCE</span><h2>Accent Colour</h2></header><div className="profile-colours">{colours.map(colour=><button key={colour.value} type="button" className={settings.appColour===colour.value?"selected":""} aria-label={`Use ${colour.name}`} title={colour.name} onClick={()=>setSettings({...settings,appColour:colour.value})}><i style={{background:colour.value,color:contrastColour(colour.value)}}>{settings.appColour===colour.value?"✓":""}</i></button>)}</div><div className="appearance-setting"><span>APP APPEARANCE</span><div>{([['light','Light'],['dark','Dark'],['system','Match system']] as const).map(([value,label])=><button type="button" key={value} className={settings.appearanceMode===value?"selected":""} onClick={()=>setSettings({...settings,appearanceMode:value})}>{label}</button>)}</div></div><div className="text-size-setting"><div><span>TEXT SIZE</span><output>{Math.round(settings.textScale*100)}%</output></div><div className="text-size-options">{([1,1.1,1.2,1.3] as TextScale[]).map((scale,index)=><button type="button" key={scale} className={settings.textScale===scale?"selected":""} aria-label={`Use ${Math.round(scale*100)} percent text size`} onClick={()=>setSettings({...settings,textScale:scale})}><b style={{fontSize:`${12+index*2}px`}}>A</b><small>{Math.round(scale*100)}%</small></button>)}</div></div></section>

      <section className="profile-section"><header><span>TRAINING</span><h2>How do you use Setra?</h2><p>Choose which training experience appears in the app. Changing this never removes your saved training data.</p></header><div className="training-preference-options">{([['strength','Strength','Strength planning, live workouts and exercise progress.'],['endurance','Endurance','Running, cycling, swimming and other endurance sessions.'],['hybrid','Hybrid','Strength and endurance shown together.']] as const).map(([value,label,description])=><button type="button" key={value} className={settings.trainingPreference===value?"selected":""} aria-pressed={settings.trainingPreference===value} onClick={()=>setSettings({...settings,trainingPreference:value})}><span>{label}</span><small>{description}</small></button>)}</div></section>

      <section className="profile-section"><header><span>CALENDAR</span><h2>Training week</h2><p>Choose your week boundary and an optional session goal. Rest days never affect an active-week streak.</p></header><label className="profile-field">START OF WEEK<select value={settings.weekStartsOn} onChange={event=>setSettings({...settings,weekStartsOn:Number(event.target.value) as ProfileSettings["weekStartsOn"]})}>{weekdayOptions.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label className="profile-field">SESSIONS PER WEEK<select value={settings.weeklySessionGoal??""} onChange={event=>setSettings({...settings,weeklySessionGoal:event.target.value?Number(event.target.value):null})}><option value="">No weekly goal</option>{Array.from({length:14},(_,index)=>index+1).map(value=><option value={value} key={value}>{value} session{value===1?"":"s"}</option>)}</select></label><small className="profile-timezone">STREAK TIMEZONE · {settings.awardsTimezone||Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC"}</small></section>

      {settings.trainingPreference!=="endurance"&&<section className="profile-section"><header><span>WORKOUTS</span><h2>Session preferences</h2></header><label className="profile-toggle"><span><b>Confirm workout times</b><small>Ask for start and finish times when completing a session.</small></span><input aria-label="Confirm workout times" type="checkbox" checked={settings.showWorkoutTimingPopup} onChange={event=>setSettings({...settings,showWorkoutTimingPopup:event.target.checked})}/><i/></label><label className="profile-toggle"><span><b>Celebrate new PBs</b><small>Show the shareable PB popup after a workout.</small></span><input aria-label="Celebrate new PBs" type="checkbox" checked={settings.showPbPopup} onChange={event=>setSettings({...settings,showPbPopup:event.target.checked})}/><i/></label></section>}

      <section className="profile-premium"><span>✦ SETRA PREMIUM</span><h2>{subscription.tier==="premium"?"Premium access active":"Go further with your training record."}</h2><p>AI Coach, personal programming, deeper reviews and advanced insights are being built around your Setra history.</p><Link href="/premium" onClick={guardNavigation}>{subscription.tier==="premium"?"View Premium":"Explore Premium"} <b>→</b></Link></section>

      <section className="profile-section profile-account"><header><span>ACCOUNT</span><h2>Your data</h2><p>Download a copy of your cloud-synced records or request account deletion. A deletion request does not remove anything immediately.</p></header><div className="profile-cloud"><i/>Your Setra data is connected to your account.</div>{pendingExportChanges>0&&<p role="status" className="profile-export-warning">{pendingExportChanges} {pendingExportChanges===1?"change is":"changes are"} still waiting to sync on this device and will not be in this download yet.</p>}<button className="profile-data-action" disabled={exportState==="preparing"||exportState==="downloading"} onClick={downloadExport}>{exportState==="preparing"?"Preparing export…":exportState==="downloading"?"Checking export…":"Download cloud data"}</button><small className="profile-export-note">Setra downloads one exact cloud snapshot, checks its final completeness, and identifies any omitted sections. Avoid editing training until it finishes for the cleanest snapshot.</small><button className="profile-delete-request" disabled={accountBusy} onClick={requestDeletion}>{accountBusy?"Requesting…":"Request account deletion"}</button><div className="profile-information-links"><Link href="/support" onClick={guardNavigation}>Support</Link><Link href="/legal" onClick={guardNavigation}>Privacy &amp; terms</Link></div><button onClick={guardedSignOut}>Sign out</button></section>
    </div>
    <footer className="profile-save"><div>{message&&<small role={exportState==="error"||exportState==="partial"?"alert":"status"}>{message}</small>}{!loading&&loadError&&<button type="button" onClick={loadProfile}>Retry loading</button>}<button disabled={!dirty||saving||loading} onClick={save}>{saving?"Saving…":dirty?"Save settings":"Settings saved ✓"}</button></div></footer>
  </main>;
}
