import type {SupabaseClient} from "@supabase/supabase-js";
import {createClient} from "@/lib/supabase/client";
import type {FriendPrivacy,FriendProfile,SharedItem,SocialConnection,SocialNotification,SocialProfile,SocialShareDraft} from "./types";

type Row=Record<string,unknown>;
const connection=(row:Row):SocialConnection=>({connectionId:String(row.connection_id),otherUserId:String(row.other_user_id),username:String(row.username||""),displayName:String(row.display_name||row.username||"Setra athlete"),avatarUrl:row.avatar_url?String(row.avatar_url):null,status:row.status as SocialConnection["status"],direction:row.direction as SocialConnection["direction"],createdAt:String(row.created_at)});

export class FriendsService{
  private supabase:SupabaseClient;
  constructor(private userId:string){this.supabase=createClient()}
  async loadIdentity(){const {data,error}=await this.supabase.from("profiles").select("username,display_name,avatar_url").eq("id",this.userId).single();if(error)throw error;return{username:String(data.username||""),displayName:String(data.display_name||""),avatarUrl:data.avatar_url?String(data.avatar_url):""}}
  async saveIdentity(username:string){const normalized=username.trim().toLowerCase().replace(/^@/,"");if(!/^[a-z0-9][a-z0-9_]{2,29}$/.test(normalized))throw new Error("Use 3–30 lowercase letters, numbers or underscores.");const {error}=await this.supabase.from("profiles").update({username:normalized}).eq("id",this.userId);if(error?.code==="23505")throw new Error("That username is already in use.");if(error)throw error;return normalized}
  async loadPrivacy():Promise<FriendPrivacy>{const {data,error}=await this.supabase.from("friend_privacy_settings").select("share_pbs,share_completed_workouts,share_training_summary").eq("user_id",this.userId).maybeSingle();if(error)throw error;return{sharePbs:Boolean(data?.share_pbs),shareCompletedWorkouts:Boolean(data?.share_completed_workouts),shareTrainingSummary:Boolean(data?.share_training_summary)}}
  async savePrivacy(value:FriendPrivacy){const {error}=await this.supabase.from("friend_privacy_settings").upsert({user_id:this.userId,share_pbs:value.sharePbs,share_completed_workouts:value.shareCompletedWorkouts,share_training_summary:value.shareTrainingSummary});if(error)throw error}
  async search(query:string):Promise<SocialProfile[]>{const {data,error}=await this.supabase.rpc("search_social_profiles",{p_query:query});if(error)throw error;return(data||[]).map((row:Row)=>({userId:String(row.user_id),username:String(row.username),displayName:String(row.display_name),avatarUrl:row.avatar_url?String(row.avatar_url):null,connectionStatus:row.connection_status as SocialProfile["connectionStatus"]}))}
  async connections():Promise<SocialConnection[]>{const {data,error}=await this.supabase.rpc("list_social_connections");if(error)throw error;return(data||[]).map(connection)}
  async friends(){return(await this.connections()).filter(item=>item.status==="accepted")}
  async sendRequest(userId:string){const {error}=await this.supabase.rpc("send_friend_request",{p_addressee:userId});if(error)throw error}
  async respond(connectionId:string,accept:boolean){const {error}=await this.supabase.rpc("respond_friend_request",{p_connection:connectionId,p_accept:accept});if(error)throw error}
  async cancel(connectionId:string){const {error}=await this.supabase.rpc("cancel_friend_request",{p_connection:connectionId});if(error)throw error}
  async remove(connectionId:string){const {error}=await this.supabase.rpc("remove_friend",{p_connection:connectionId});if(error)throw error}
  async block(userId:string){const {error}=await this.supabase.rpc("block_social_user",{p_user:userId});if(error)throw error}
  async unblock(connectionId:string){const {error}=await this.supabase.rpc("unblock_social_user",{p_connection:connectionId});if(error)throw error}
  async share(recipientId:string,draft:SocialShareDraft){const {error}=await this.supabase.rpc("share_social_item",{p_recipient:recipientId,p_item_type:draft.itemType,p_source_client_id:draft.sourceClientId,p_title:draft.title,p_snapshot:draft.snapshot});if(error)throw error}
  async sharedWithMe():Promise<SharedItem[]>{const {data,error}=await this.supabase.from("social_shared_items").select("*").eq("recipient_user_id",this.userId).neq("recipient_status","dismissed").order("created_at",{ascending:false});if(error)throw error;return(data||[]).map((row:Row)=>({id:String(row.id),senderUserId:String(row.sender_user_id),recipientUserId:String(row.recipient_user_id),itemType:row.item_type as SharedItem["itemType"],sourceClientId:row.source_client_id?String(row.source_client_id):null,title:String(row.title),snapshot:row.snapshot as Record<string,unknown>,recipientStatus:row.recipient_status as SharedItem["recipientStatus"],createdAt:String(row.created_at)}))}
  async updateSharedItem(id:string,status:"viewed"|"saved"|"dismissed"){const update:Record<string,string>={recipient_status:status,viewed_at:new Date().toISOString()};if(status==="saved")update.saved_at=new Date().toISOString();const {error}=await this.supabase.from("social_shared_items").update(update).eq("id",id).eq("recipient_user_id",this.userId);if(error)throw error}
  async friendProfile(userId:string):Promise<FriendProfile>{const {data,error}=await this.supabase.rpc("get_friend_profile",{p_friend:userId});if(error)throw error;return data as FriendProfile}
  async notifications():Promise<SocialNotification[]>{const {data,error}=await this.supabase.rpc("list_social_notifications");if(error)throw error;return(data||[]).map((row:Row)=>({notificationId:String(row.notification_id),notificationType:row.notification_type as SocialNotification["notificationType"],actorUserId:String(row.actor_user_id),actorUsername:String(row.actor_username),actorDisplayName:String(row.actor_display_name),sharedItemId:row.shared_item_id?String(row.shared_item_id):null,createdAt:String(row.created_at),readAt:row.read_at?String(row.read_at):null}))}
  async markNotificationsRead(){const {error}=await this.supabase.from("social_notifications").update({read_at:new Date().toISOString()}).eq("recipient_user_id",this.userId).is("read_at",null);if(error)throw error}
}
