import type {TrainingActivityType,TrainingSessionBlock,TrainingTargetMetric} from "@/lib/setra/types";

export const formatStepClock=(seconds?:number)=>seconds==null?"":`${Math.floor(seconds/60)}:${String(Math.round(seconds%60)).padStart(2,"0")}`;
export const parseStepClock=(value:string)=>{const clean=value.trim();if(!clean)return undefined;const parts=clean.split(":").map(Number);if(parts.some(Number.isNaN))return undefined;return parts.length===1?parts[0]*60:parts[0]*60+parts[1]};
export const formatStepTime=(seconds:number)=>seconds%3600===0?`${seconds/3600} hr`:seconds%60===0?`${seconds/60} min`:`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`;
export const stepDistanceUsesMetres=(activity:TrainingActivityType)=>activity==="swim"||activity==="row";
export const displayStepDistance=(metres:number|undefined,activity:TrainingActivityType)=>metres==null?"":String(stepDistanceUsesMetres(activity)?metres:Number((metres/1000).toFixed(3)));
export const stepTargetUnit=(activity:TrainingActivityType,metric:TrainingTargetMetric)=>metric==="pace"?(activity==="swim"?"seconds_per_100m":activity==="row"?"seconds_per_500m":"seconds_per_km"):metric==="speed"?"km_per_hour":metric==="heart_rate"?"bpm":metric==="heart_rate_zone"?"hr_zone":metric==="power"?"watts":metric==="power_zone"?"power_zone":metric==="cadence"?(activity==="row"?"spm":"rpm"):metric==="rpe"?"rpe":metric;
export const stepTargetSuffix=(unit?:string)=>unit==="seconds_per_100m"?"/100 m":unit==="seconds_per_500m"?"/500 m":unit==="seconds_per_km"?"/km":unit==="km_per_hour"?"km/h":unit==="bpm"?"bpm":unit==="watts"?"W":unit==="rpm"?"rpm":unit==="spm"?"spm":unit==="rpe"?"/10":"";

export const enduranceTargetOptions=(activity:TrainingActivityType):[TrainingTargetMetric,string][]=>{
  const common:[TrainingTargetMetric,string][]=[["heart_rate","Heart-rate range"],["heart_rate_zone","Heart-rate zone"],["rpe","RPE"],["effort","Easy / free effort"],["custom","Custom target"]];
  if(activity==="bike")return [["speed","Speed range"],["power","Power range"],["power_zone","Power zone"],["cadence","Cadence range"],...common];
  if(activity==="row")return [["pace","/500 m split"],["power","Power range"],["power_zone","Power zone"],["cadence","Stroke-rate range"],...common];
  if(activity==="swim")return [["pace","Pace /100 m"],["cadence","Stroke-rate range"],...common];
  if(activity==="run"||activity==="walk_hike")return [["pace","Pace range"],["speed","Speed range"],["cadence","Cadence range"],...common];
  return [["speed","Speed range"],["power","Power range"],["cadence","Cadence range"],...common];
};

export const childrenOf=(blocks:TrainingSessionBlock[],parentId?:string)=>blocks.filter(block=>(block.parentId||undefined)===parentId);
export const descendantIds=(blocks:TrainingSessionBlock[],id:string):Set<string>=>{const found=new Set<string>();const visit=(parent:string)=>childrenOf(blocks,parent).forEach(child=>{if(found.has(child.id))return;found.add(child.id);visit(child.id)});visit(id);return found};
export const flattenBlockTree=(blocks:TrainingSessionBlock[]):TrainingSessionBlock[]=>{const output:TrainingSessionBlock[]=[];const seen=new Set<string>();const visit=(parentId?:string)=>childrenOf(blocks,parentId).forEach(block=>{if(seen.has(block.id))return;seen.add(block.id);output.push(block);visit(block.id)});visit();blocks.forEach(block=>{if(!seen.has(block.id))output.push({...block,parentId:undefined})});return output};
export const moveBlockAmongSiblings=(blocks:TrainingSessionBlock[],id:string,direction:-1|1)=>{const block=blocks.find(item=>item.id===id);if(!block)return blocks;const siblings=childrenOf(blocks,block.parentId);const index=siblings.findIndex(item=>item.id===id);const target=index+direction;if(target<0||target>=siblings.length)return blocks;[siblings[index],siblings[target]]=[siblings[target],siblings[index]];const output:TrainingSessionBlock[]=[];const seen=new Set<string>();const visit=(parentId?:string)=>{const level=parentId===block.parentId?siblings:childrenOf(blocks,parentId);level.forEach(item=>{if(seen.has(item.id))return;seen.add(item.id);output.push(item);visit(item.id)})};visit();blocks.forEach(item=>{if(!seen.has(item.id))output.push({...item,parentId:undefined})});return output};
export const duplicateBlockTree=(blocks:TrainingSessionBlock[],id:string)=>{const source=blocks.find(block=>block.id===id);if(!source)return blocks;const ids=new Set([id,...descendantIds(blocks,id)]);const copies=blocks.filter(block=>ids.has(block.id));const idMap=new Map(copies.map(block=>[block.id,`${block.type}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`]));const cloned=copies.map(block=>({...structuredClone(block),id:idMap.get(block.id)!,title:block===source?`${block.title||"Step"} copy`:block.title,parentId:block.parentId===source.parentId?source.parentId:idMap.get(block.parentId||"")}));const flattened=flattenBlockTree(blocks);const subtreeEnd=flattened.reduce((last,block,index)=>ids.has(block.id)?index:last,-1);flattened.splice(subtreeEnd+1,0,...cloned);return flattenBlockTree(flattened)};

export function formatTrainingStep(block:TrainingSessionBlock,activity:TrainingActivityType){
  const repeats=Math.max(1,block.repetitions||1);if(block.type==="repeat_group")return `Repeat ×${repeats}`;
  const parts:string[]=[];if(repeats>1)parts.push(`${repeats} ×`);if(block.completionType==="time"&&block.durationSeconds)parts.push(formatStepTime(block.durationSeconds));else if(block.completionType==="distance"&&block.distanceMetres!=null)parts.push(stepDistanceUsesMetres(activity)?`${block.distanceMetres} m`:`${Number((block.distanceMetres/1000).toFixed(2))} km`);else if(block.completionType==="lap_button")parts.push("until lap press");
  if((block.targetMetric==="effort"||block.targetMetric==="custom")&&block.intensityTarget)parts.push(block.intensityTarget);else if((block.targetMetric==="heart_rate_zone"||block.targetMetric==="power_zone")&&block.targetMinValue!=null)parts.push(`Zone ${block.targetMinValue}`);else if(block.targetMetric&&block.targetMinValue!=null){const low=block.targetMetric==="pace"?formatStepClock(block.targetMinValue):Number(block.targetMinValue.toFixed(1));const high=block.targetMaxValue==null?low:block.targetMetric==="pace"?formatStepClock(block.targetMaxValue):Number(block.targetMaxValue.toFixed(1));parts.push(`${low}${high!==low?`–${high}`:""} ${stepTargetSuffix(block.targetUnit)}`.trim())}
  if(block.stroke)parts.push(block.stroke);if(block.recoveryDurationSeconds)parts.push(`recover ${formatStepTime(block.recoveryDurationSeconds)}`);else if(block.recoveryDistanceMetres)parts.push(`recover ${stepDistanceUsesMetres(activity)?`${block.recoveryDistanceMetres} m`:`${Number((block.recoveryDistanceMetres/1000).toFixed(2))} km`}`);return parts.join(" · ")||block.instructions||"Open / manual lap";
}

export function calculateStructuredTotals(blocks:TrainingSessionBlock[]){const calculate=(parentId:string|undefined,multiplier:number):{distanceMetres:number;durationSeconds:number}=>childrenOf(blocks,parentId).reduce((total,block)=>{const repeats=Math.max(1,block.repetitions||1);if(block.type==="repeat_group"){const nested=calculate(block.id,multiplier*repeats);return {distanceMetres:total.distanceMetres+nested.distanceMetres,durationSeconds:total.durationSeconds+nested.durationSeconds}}return {distanceMetres:total.distanceMetres+multiplier*repeats*((block.distanceMetres||0)+(block.recoveryDistanceMetres||0)),durationSeconds:total.durationSeconds+multiplier*repeats*((block.durationSeconds||0)+(block.recoveryDurationSeconds||0))}},{distanceMetres:0,durationSeconds:0});return calculate(undefined,1)}
