export type Exercise = { id: string; name: string; group: string; equipment: string };
export type WarmupItem = { id: string; kind: "exercise"|"instruction"; exerciseId?: string; title?: string; instructions: string; done?: boolean };
export type TemplateExercise = { exerciseId: string; sets: number; reps: string; group?: string; note?: string };
export type Template = { id: string; name: string; focus: string; warmup?: WarmupItem[]; exercises: TemplateExercise[]; color?: string; icon?: string; supersetNames?: Record<string,string> };
export type SetLog = { reps: string; weight: string; rpe: string; done: boolean; note?: string };
// `text` is retained for diaries saved before BAND became its user-facing name.
export type LoadMode = "kg"|"band"|"bw"|"text";
export type WorkoutExercise = { exerciseId: string; sets: SetLog[]; note: string; group?: string; loadMode?: LoadMode; planNote?: string; repTarget?: string; skipped?: boolean };
export type Workout = { id: string; templateId?: string; name: string; date: string; startedAt: string; endedAt?: string; duration: number; warmup?: WarmupItem[]; exercises: WorkoutExercise[]; note: string; supersetNames?: Record<string,string> };
export type ScheduledWorkout = { date: string; templateId: string; skipped?: boolean };
export type AppData = { exercises: Exercise[]; templates: Template[]; workouts: Workout[]; scheduled: ScheduledWorkout[] };
export type CloudSyncState = "local" | "loading" | "synced" | "error";

export type TrainingPreference = "strength"|"endurance"|"hybrid";
export type TrainingActivityType = "run"|"bike"|"swim"|"row"|"walk_hike"|"elliptical"|"cross_training"|"custom";
export type TrainingSessionStatus = "planned"|"in_progress"|"completed"|"cancelled";
export type TrainingBlockType = "warmup"|"main"|"interval"|"recovery"|"rest"|"cooldown"|"custom"|"repeat_group";
export type TrainingCompletionType = "open"|"time"|"distance"|"lap_button";
export type TrainingTargetMetric = "pace"|"speed"|"heart_rate"|"heart_rate_zone"|"power"|"power_zone"|"cadence"|"rpe"|"effort"|"custom";
export type TrainingEnvironment = "unspecified"|"outdoor"|"indoor"|"treadmill"|"track"|"pool"|"open_water"|"trainer"|"erg";
export type TrainingCategory = "easy"|"long"|"tempo"|"threshold"|"intervals"|"recovery"|"race"|"technique"|"custom";
export type TrainingSessionBlock = {
  id:string;
  type:TrainingBlockType;
  title:string;
  instructions:string;
  repetitions?:number;
  durationSeconds?:number;
  distanceMetres?:number;
  recoveryDurationSeconds?:number;
  recoveryDistanceMetres?:number;
  intensityTarget?:string;
  completionType?:TrainingCompletionType;
  targetMetric?:TrainingTargetMetric;
  targetMinValue?:number;
  targetMaxValue?:number;
  targetUnit?:string;
  stroke?:string;
  providerMetadata?:Record<string,unknown>;
  parentId?:string;
};
export type EnduranceSession = {
  id:string;
  activityType:TrainingActivityType;
  status:TrainingSessionStatus;
  title:string;
  date:string;
  plannedStartTime?:string;
  plannedDurationMinutes?:number;
  plannedDistanceKm?:number;
  targetRpe?:number;
  environment?:TrainingEnvironment;
  category?:TrainingCategory;
  plannedSessionId?:string;
  startedAt?:string;
  endedAt?:string;
  durationMinutes?:number;
  distanceKm?:number;
  averagePaceSecondsPerKm?:number;
  averageSpeedKph?:number;
  averageSplitSecondsPer500m?:number;
  rpe?:number;
  averageHeartRate?:number;
  elevationGainMetres?:number;
  notes:string;
  blocks:TrainingSessionBlock[];
  source?:string;
  externalProvider?:string;
  externalActivityId?:string;
  completedAt?:string;
};
