-- Setra's shared exercise catalogue. Safe to run more than once.
with catalogue (id,name,muscle_group,equipment) as (
 values
  ('pec-deck-chest-fly','Machine Chest Fly','Chest','Machine'),
  ('dumbbell-chest-fly','Dumbbell Chest Fly','Chest','Dumbbell'),
  ('incline-dumbbell-chest-fly','Incline Dumbbell Chest Fly','Chest','Dumbbell'),
  ('barbell-shrug','Barbell Shrug','Traps','Barbell'),
  ('dumbbell-shrug','Dumbbell Shrug','Traps','Dumbbell'),
  ('cable-shrug','Cable Shrug','Traps','Cable'),
  ('machine-shrug','Machine Shrug','Traps','Machine'),
  ('trap-bar-shrug','Trap Bar Shrug','Traps','Trap Bar'),
  ('prone-trap-raise','Prone Trap Raise','Traps','Dumbbell'),
  ('side-plank','Side Plank','Obliques','Bodyweight'),
  ('side-plank-hip-dip','Side Plank Hip Dip','Obliques','Bodyweight'),
  ('russian-twist','Russian Twist','Obliques','Bodyweight'),
  ('cable-wood-chop','Cable Wood Chop','Obliques','Cable'),
  ('cable-reverse-wood-chop','Cable Reverse Wood Chop','Obliques','Cable'),
  ('landmine-rotation','Landmine Rotation','Obliques','Barbell'),
  ('dumbbell-side-bend','Dumbbell Side Bend','Obliques','Dumbbell'),
  ('pallof-isometric-hold','Pallof Press Isometric Hold','Obliques','Cable'),
  ('barbell-wrist-curl','Barbell Wrist Curl','Forearms','Barbell'),
  ('dumbbell-wrist-curl','Dumbbell Wrist Curl','Forearms','Dumbbell'),
  ('reverse-wrist-curl','Dumbbell Reverse Wrist Curl','Forearms','Dumbbell'),
  ('wrist-roller','Wrist Roller','Forearms','Other'),
  ('plate-pinch','Plate Pinch','Forearms','Plate'),
  ('reverse-barbell-curl','Reverse Barbell Curl','Forearms','Barbell'),
  ('dead-hang','Dead Hang','Forearms','Bodyweight'),
  ('wall-sit-hold','Wall Sit Isometric Hold','Quads','Bodyweight'),
  ('squat-isometric-hold','Squat Isometric Hold','Quads','Bodyweight'),
  ('split-squat-isometric-hold','Split Squat Isometric Hold','Quads','Bodyweight'),
  ('glute-bridge-isometric-hold','Glute Bridge Isometric Hold','Glutes','Bodyweight'),
  ('calf-raise-isometric-hold','Calf Raise Isometric Hold','Calves','Bodyweight'),
  ('push-up-isometric-hold','Push Up Isometric Hold','Chest','Bodyweight'),
  ('pull-up-isometric-hold','Pull Up Isometric Hold','Back','Bodyweight'),
  ('hollow-body-hold','Hollow Body Hold','Core','Bodyweight'),
  ('assisted-dip','Assisted Dip','Chest','Assisted'),
  ('band-assisted-bench-press','Band-Assisted Bench Press','Chest','Resistance Band'),
  ('bar-dip','Bar Dip','Chest','Bodyweight'),
  ('bench-press','Bench Press','Chest','Barbell'),
  ('bench-press-against-band','Bench Press Against Band','Chest','Resistance Band'),
  ('board-press','Board Press','Chest','Barbell'),
  ('cable-chest-press','Cable Chest Press','Chest','Cable'),
  ('clap-push-up','Clap Push-Up','Chest','Bodyweight'),
  ('close-grip-bench-press','Close-Grip Bench Press','Chest','Barbell'),
  ('close-grip-feet-up-bench-press','Close-Grip Feet-Up Bench Press','Chest','Barbell'),
  ('cobra-push-up','Cobra Push-Up','Chest','Bodyweight'),
  ('decline-bench-press','Decline Bench Press','Chest','Barbell'),
  ('decline-push-up','Decline Push-Up','Chest','Bodyweight'),
  ('dumbbell-chest-press','Dumbbell Chest Press','Chest','Dumbbell'),
  ('dumbbell-decline-chest-press','Dumbbell Decline Chest Press','Chest','Dumbbell'),
  ('dumbbell-floor-press','Dumbbell Floor Press','Chest','Dumbbell'),
  ('dumbbell-pullover','Dumbbell Pullover','Chest','Dumbbell'),
  ('feet-up-bench-press','Feet-Up Bench Press','Chest','Barbell'),
  ('floor-press','Floor Press','Chest','Barbell'),
  ('incline-bench-press','Incline Bench Press','Chest','Barbell'),
  ('incline-dumbbell-press','Incline Dumbbell Press','Chest','Dumbbell'),
  ('incline-push-up','Incline Push-Up','Chest','Bodyweight'),
  ('kettlebell-floor-press','Kettlebell Floor Press','Chest','Kettlebell'),
  ('kneeling-incline-push-up','Kneeling Incline Push-Up','Chest','Bodyweight'),
  ('kneeling-push-up','Kneeling Push-Up','Chest','Bodyweight'),
  ('machine-chest-press','Machine Chest Press','Chest','Machine'),
  ('medicine-ball-chest-pass','Medicine Ball Chest Pass','Chest','Medicine Ball'),
  ('pec-deck','Pec Deck','Chest','Machine'),
  ('pin-bench-press','Pin Bench Press','Chest','Barbell'),
  ('plank-to-push-up','Plank to Push-Up','Chest','Bodyweight'),
  ('push-up','Push-Up','Chest','Bodyweight'),
  ('push-up-against-wall','Push-Up Against Wall','Chest','Bodyweight'),
  ('push-ups-with-feet-in-rings','Push-Ups With Feet in Rings','Chest','Gymnastic Rings'),
  ('resistance-band-chest-fly','Resistance Band Chest Fly','Chest','Resistance Band'),
  ('ring-dip','Ring Dip','Chest','Gymnastic Rings'),
  ('seated-cable-chest-fly','Seated Cable Chest Fly','Chest','Cable'),
  ('smith-machine-bench-press','Smith Machine Bench Press','Chest','Smith Machine'),
  ('smith-machine-incline-bench-press','Smith Machine Incline Bench Press','Chest','Smith Machine'),
  ('smith-machine-reverse-grip-bench-press','Smith Machine Reverse Grip Bench Press','Chest','Smith Machine'),
  ('standing-cable-chest-fly','Standing Cable Chest Fly','Chest','Cable'),
  ('standing-resistance-band-chest-fly','Standing Resistance Band Chest Fly','Chest','Resistance Band'),
  ('arnold-press','Arnold Press','Shoulders','Bodyweight'),
  ('band-external-shoulder-rotation','Band External Shoulder Rotation','Shoulders','Resistance Band'),
  ('band-internal-shoulder-rotation','Band Internal Shoulder Rotation','Shoulders','Resistance Band'),
  ('band-pull-apart','Band Pull-Apart','Shoulders','Resistance Band'),
  ('banded-face-pull','Banded Face Pull','Shoulders','Resistance Band'),
  ('barbell-front-raise','Barbell Front Raise','Shoulders','Barbell'),
  ('barbell-rear-delt-row','Barbell Rear Delt Row','Shoulders','Barbell'),
  ('barbell-upright-row','Barbell Upright Row','Shoulders','Barbell'),
  ('behind-the-neck-press','Behind the Neck Press','Shoulders','Bodyweight'),
  ('cable-internal-shoulder-rotation','Cable Internal Shoulder Rotation','Shoulders','Cable'),
  ('cable-external-shoulder-rotation','Cable External Shoulder Rotation','Shoulders','Cable'),
  ('cable-front-raise','Cable Front Raise','Shoulders','Cable'),
  ('cable-lateral-raise','Cable Lateral Raise','Shoulders','Cable'),
  ('cable-rear-delt-row','Cable Rear Delt Row','Shoulders','Cable'),
  ('cuban-press','Cuban Press','Shoulders','Bodyweight'),
  ('devils-press','Devils Press','Shoulders','Dumbbell'),
  ('dumbbell-front-raise','Dumbbell Front Raise','Shoulders','Dumbbell'),
  ('dumbbell-horizontal-internal-shoulder-rotation','Dumbbell Horizontal Internal Shoulder Rotation','Shoulders','Dumbbell'),
  ('dumbbell-horizontal-external-shoulder-rotation','Dumbbell Horizontal External Shoulder Rotation','Shoulders','Dumbbell'),
  ('dumbbell-lateral-raise','Dumbbell Lateral Raise','Shoulders','Dumbbell'),
  ('dumbbell-rear-delt-row','Dumbbell Rear Delt Row','Shoulders','Dumbbell'),
  ('dumbbell-shoulder-press','Dumbbell Shoulder Press','Shoulders','Dumbbell'),
  ('face-pull','Face Pull','Shoulders','Bodyweight'),
  ('front-hold','Front Hold','Shoulders','Bodyweight'),
  ('handstand-push-up','Handstand Push-Up','Shoulders','Bodyweight'),
  ('jerk','Jerk','Shoulders','Barbell'),
  ('kettlebell-halo','Kettlebell Halo','Shoulders','Kettlebell'),
  ('kettlebell-press','Kettlebell Press','Shoulders','Kettlebell'),
  ('kettlebell-push-press','Kettlebell Push Press','Shoulders','Kettlebell'),
  ('landmine-press','Landmine Press','Shoulders','Landmine'),
  ('lying-dumbbell-external-shoulder-rotation','Lying Dumbbell External Shoulder Rotation','Shoulders','Dumbbell'),
  ('lying-dumbbell-internal-shoulder-rotation','Lying Dumbbell Internal Shoulder Rotation','Shoulders','Dumbbell'),
  ('machine-lateral-raise','Machine Lateral Raise','Shoulders','Machine'),
  ('machine-shoulder-press','Machine Shoulder Press','Shoulders','Machine'),
  ('monkey-row','Monkey Row','Shoulders','Bodyweight'),
  ('one-arm-landmine-press','One-Arm Landmine Press','Shoulders','Landmine'),
  ('overhead-press','Overhead Press','Shoulders','Barbell'),
  ('plate-front-raise','Plate Front Raise','Shoulders','Plate'),
  ('poliquin-raise','Poliquin Raise','Shoulders','Bodyweight'),
  ('power-jerk','Power Jerk','Shoulders','Barbell'),
  ('push-press','Push Press','Shoulders','Barbell'),
  ('resistance-band-lateral-raise','Resistance Band Lateral Raise','Shoulders','Resistance Band'),
  ('reverse-cable-flyes','Reverse Cable Flyes','Shoulders','Cable'),
  ('reverse-dumbbell-flyes','Reverse Dumbbell Flyes','Shoulders','Dumbbell'),
  ('reverse-dumbbell-flyes-on-incline-bench','Reverse Dumbbell Flyes on Incline Bench','Shoulders','Dumbbell'),
  ('reverse-machine-fly','Reverse Machine Fly','Shoulders','Machine'),
  ('seated-dumbbell-shoulder-press','Seated Dumbbell Shoulder Press','Shoulders','Dumbbell'),
  ('seated-barbell-overhead-press','Seated Barbell Overhead Press','Shoulders','Barbell'),
  ('seated-kettlebell-press','Seated Kettlebell Press','Shoulders','Kettlebell'),
  ('seated-smith-machine-shoulder-press','Seated Smith Machine Shoulder Press','Shoulders','Smith Machine'),
  ('smith-machine-landmine-press','Smith Machine Landmine Press','Shoulders','Smith Machine'),
  ('snatch-grip-behind-the-neck-press','Snatch Grip Behind the Neck Press','Shoulders','Bodyweight'),
  ('squat-jerk','Squat Jerk','Shoulders','Barbell'),
  ('split-jerk','Split Jerk','Shoulders','Barbell'),
  ('turkish-get-up','Turkish Get-Up','Shoulders','Bodyweight'),
  ('wall-walk','Wall Walk','Shoulders','Bodyweight'),
  ('z-press','Z Press','Shoulders','Barbell'),
  ('barbell-curl','Barbell Curl','Biceps','Barbell'),
  ('barbell-preacher-curl','Barbell Preacher Curl','Biceps','Barbell'),
  ('bayesian-curl','Bayesian Curl','Biceps','Bodyweight'),
  ('bodyweight-curl','Bodyweight Curl','Biceps','Bodyweight'),
  ('cable-crossover-bicep-curl','Cable Crossover Bicep Curl','Biceps','Cable'),
  ('cable-curl-with-bar','Cable Curl With Bar','Biceps','Cable'),
  ('cable-curl-with-rope','Cable Curl With Rope','Biceps','Cable'),
  ('concentration-curl','Concentration Curl','Biceps','Bodyweight'),
  ('drag-curl','Drag Curl','Biceps','Bodyweight'),
  ('dumbbell-curl','Dumbbell Curl','Biceps','Dumbbell'),
  ('dumbbell-preacher-curl','Dumbbell Preacher Curl','Biceps','Dumbbell'),
  ('ez-curl','EZ Curl','Biceps','EZ Bar'),
  ('hammer-curl','Hammer Curl','Biceps','Bodyweight'),
  ('incline-dumbbell-curl','Incline Dumbbell Curl','Biceps','Dumbbell'),
  ('kettlebell-curl','Kettlebell Curl','Biceps','Kettlebell'),
  ('lying-bicep-cable-curl-on-bench','Lying Bicep Cable Curl on Bench','Biceps','Cable'),
  ('lying-bicep-cable-curl-on-floor','Lying Bicep Cable Curl on Floor','Biceps','Cable'),
  ('machine-bicep-curl','Machine Bicep Curl','Biceps','Machine'),
  ('overhead-cable-curl','Overhead Cable Curl','Biceps','Cable'),
  ('reverse-dumbbell-curl','Reverse Dumbbell Curl','Biceps','Dumbbell'),
  ('resistance-band-curl','Resistance Band Curl','Biceps','Resistance Band'),
  ('spider-curl','Spider Curl','Biceps','Bodyweight'),
  ('zottman-curl','Zottman Curl','Biceps','Bodyweight'),
  ('barbell-standing-triceps-extension','Barbell Standing Triceps Extension','Triceps','Barbell'),
  ('barbell-incline-triceps-extension','Barbell Incline Triceps Extension','Triceps','Barbell'),
  ('barbell-lying-triceps-extension','Barbell Lying Triceps Extension','Triceps','Barbell'),
  ('bench-dip','Bench Dip','Triceps','Bodyweight'),
  ('crossbody-cable-triceps-extension','Crossbody Cable Triceps Extension','Triceps','Cable'),
  ('close-grip-push-up','Close-Grip Push-Up','Triceps','Bodyweight'),
  ('dumbbell-lying-triceps-extension','Dumbbell Lying Triceps Extension','Triceps','Dumbbell'),
  ('dumbbell-standing-triceps-extension','Dumbbell Standing Triceps Extension','Triceps','Dumbbell'),
  ('ez-bar-lying-triceps-extension','EZ Bar Lying Triceps Extension','Triceps','EZ Bar'),
  ('machine-overhead-triceps-extension','Machine Overhead Triceps Extension','Triceps','Machine'),
  ('overhead-cable-triceps-extension-lower-position','Overhead Cable Triceps Extension (Lower Position)','Triceps','Cable'),
  ('overhead-cable-triceps-extension-upper-position','Overhead Cable Triceps Extension (Upper Position)','Triceps','Cable'),
  ('smith-machine-skull-crushers','Smith Machine Skull Crushers','Triceps','Smith Machine'),
  ('tate-press','Tate Press','Triceps','Bodyweight'),
  ('tricep-bodyweight-extension','Tricep Bodyweight Extension','Triceps','Bodyweight'),
  ('tricep-pushdown-with-bar','Tricep Pushdown With Bar','Triceps','Cable'),
  ('tricep-pushdown-with-rope','Tricep Pushdown With Rope','Triceps','Cable'),
  ('air-squat','Air Squat','Quads','Barbell'),
  ('barbell-hack-squat','Barbell Hack Squat','Quads','Barbell'),
  ('barbell-lunge','Barbell Lunge','Quads','Barbell'),
  ('barbell-walking-lunge','Barbell Walking Lunge','Quads','Barbell'),
  ('belt-squat','Belt Squat','Quads','Barbell'),
  ('body-weight-lunge','Body Weight Lunge','Quads','Bodyweight'),
  ('box-jump','Box Jump','Quads','Bodyweight'),
  ('box-squat','Box Squat','Quads','Barbell'),
  ('bulgarian-split-squat','Bulgarian Split Squat','Quads','Barbell'),
  ('chair-squat','Chair Squat','Quads','Barbell'),
  ('curtsy-lunge','Curtsy Lunge','Quads','Bodyweight'),
  ('depth-jump','Depth Jump','Quads','Bodyweight'),
  ('dumbbell-lunge','Dumbbell Lunge','Quads','Dumbbell'),
  ('dumbbell-walking-lunge','Dumbbell Walking Lunge','Quads','Dumbbell'),
  ('dumbbell-squat','Dumbbell Squat','Quads','Dumbbell'),
  ('front-squat','Front Squat','Quads','Barbell'),
  ('goblet-squat','Goblet Squat','Quads','Barbell'),
  ('ground-to-overhead','Ground to Overhead','Quads','Barbell'),
  ('hack-squat-machine','Hack Squat Machine','Quads','Machine'),
  ('half-air-squat','Half Air Squat','Quads','Barbell'),
  ('jump-squat','Jump Squat','Quads','Barbell'),
  ('jumping-lunge','Jumping Lunge','Quads','Bodyweight'),
  ('kettlebell-front-squat','Kettlebell Front Squat','Quads','Kettlebell'),
  ('kettlebell-thrusters','Kettlebell Thrusters','Quads','Kettlebell'),
  ('landmine-hack-squat','Landmine Hack Squat','Quads','Landmine'),
  ('landmine-squat','Landmine Squat','Quads','Landmine'),
  ('lateral-bound','Lateral Bound','Quads','Bodyweight'),
  ('leg-extension','Leg Extension','Quads','Bodyweight'),
  ('leg-press','Leg Press','Quads','Machine'),
  ('one-legged-leg-extension','One-Legged Leg Extension','Quads','Bodyweight'),
  ('pause-squat','Pause Squat','Quads','Barbell'),
  ('pendulum-squat','Pendulum Squat','Quads','Machine'),
  ('pin-squat','Pin Squat','Quads','Barbell'),
  ('pistol-squat','Pistol Squat','Quads','Barbell'),
  ('poliquin-step-up','Poliquin Step-Up','Quads','Bodyweight'),
  ('prisoner-get-up','Prisoner Get Up','Quads','Bodyweight'),
  ('reverse-barbell-lunge','Reverse Barbell Lunge','Quads','Barbell'),
  ('reverse-body-weight-lunge','Reverse Body Weight Lunge','Quads','Bodyweight'),
  ('reverse-dumbbell-lunge','Reverse Dumbbell Lunge','Quads','Dumbbell'),
  ('reverse-nordic','Reverse Nordic','Quads','Bodyweight'),
  ('safety-bar-squat','Safety Bar Squat','Quads','Safety Bar'),
  ('shallow-body-weight-lunge','Shallow Body Weight Lunge','Quads','Bodyweight'),
  ('side-lunges-bodyweight','Side Lunges (Bodyweight)','Quads','Bodyweight'),
  ('smith-machine-bulgarian-split-squat','Smith Machine Bulgarian Split Squat','Quads','Smith Machine'),
  ('smith-machine-front-squat','Smith Machine Front Squat','Quads','Smith Machine'),
  ('smith-machine-lunge','Smith Machine Lunge','Quads','Smith Machine'),
  ('smith-machine-squat','Smith Machine Squat','Quads','Smith Machine'),
  ('sumo-squat','Sumo Squat','Quads','Barbell'),
  ('squat','Squat','Quads','Barbell'),
  ('standing-cable-leg-extension','Standing Cable Leg Extension','Quads','Cable'),
  ('step-up','Step Up','Quads','Bodyweight'),
  ('vertical-leg-press','Vertical Leg Press','Quads','Machine'),
  ('zercher-squat','Zercher Squat','Quads','Barbell'),
  ('zombie-squat','Zombie Squat','Quads','Barbell'),
  ('bodyweight-leg-curl','Bodyweight Leg Curl','Hamstrings','Bodyweight'),
  ('glute-ham-raise','Glute Ham Raise','Hamstrings','Bodyweight'),
  ('leg-curl-on-ball','Leg Curl On Ball','Hamstrings','Bodyweight'),
  ('lying-leg-curl','Lying Leg Curl','Hamstrings','Bodyweight'),
  ('nordic-hamstring-eccentric','Nordic Hamstring Eccentric','Hamstrings','Gymnastic Rings'),
  ('one-legged-lying-leg-curl','One-Legged Lying Leg Curl','Hamstrings','Bodyweight'),
  ('one-legged-seated-leg-curl','One-Legged Seated Leg Curl','Hamstrings','Bodyweight'),
  ('romanian-deadlift','Romanian Deadlift','Hamstrings','Barbell'),
  ('seated-leg-curl','Seated Leg Curl','Hamstrings','Bodyweight'),
  ('smith-machine-romanian-deadlift','Smith Machine Romanian Deadlift','Hamstrings','Smith Machine'),
  ('standing-leg-curl','Standing Leg Curl','Hamstrings','Bodyweight'),
  ('banded-hip-march','Banded Hip March','Hip Flexors','Resistance Band'),
  ('standing-hip-flexor-raise','Standing Hip Flexor Raise','Hip Flexors','Bodyweight'),
  ('cable-machine-hip-adduction','Cable Machine Hip Adduction','Adductors','Cable'),
  ('hip-adduction-against-band','Hip Adduction Against Band','Adductors','Resistance Band'),
  ('machine-hip-adduction','Hip Adduction Machine','Adductors','Machine'),
  ('long-lever-copenhagen-hold','Long Lever Copenhagen Hold','Adductors','Bodyweight'),
  ('short-lever-copenhagen-hold','Short Lever Copenhagen Hold','Adductors','Bodyweight'),
  ('heel-walk','Heel Walk','Tibialis','Bodyweight'),
  ('kettlebell-tibialis-raise','Kettlebell Tibialis Raise','Tibialis','Kettlebell'),
  ('tibialis-band-pull','Tibialis Band Pull','Tibialis','Resistance Band'),
  ('tibialis-raise','Tibialis Raise','Tibialis','Bodyweight'),
  ('assisted-chin-up','Assisted Chin-Up','Back','Assisted'),
  ('assisted-pull-up','Assisted Pull-Up','Back','Assisted'),
  ('back-extension','Back Extension','Back','Bodyweight'),
  ('banded-muscle-up','Banded Muscle-Up','Back','Resistance Band'),
  ('barbell-row','Barbell Row','Back','Barbell'),
  ('block-clean','Block Clean','Back','Barbell'),
  ('block-snatch','Block Snatch','Back','Barbell'),
  ('cable-close-grip-seated-row','Cable Close Grip Seated Row','Back','Cable'),
  ('cable-wide-grip-seated-row','Cable Wide Grip Seated Row','Back','Cable'),
  ('chest-supported-dumbbell-row','Chest-Supported Dumbbell Row','Back','Dumbbell'),
  ('chest-to-bar','Chest to Bar','Back','Bodyweight'),
  ('chin-up','Chin-Up','Back','Bodyweight'),
  ('clean','Clean','Back','Barbell'),
  ('clean-and-jerk','Clean and Jerk','Back','Barbell'),
  ('close-grip-chin-up','Close-Grip Chin-Up','Back','Bodyweight'),
  ('close-grip-lat-pulldown','Close-Grip Lat Pulldown','Back','Cable'),
  ('deadlift','Deadlift','Back','Barbell'),
  ('deficit-deadlift','Deficit Deadlift','Back','Barbell'),
  ('dumbbell-deadlift','Dumbbell Deadlift','Back','Dumbbell'),
  ('dumbbell-row','Dumbbell Row','Back','Dumbbell'),
  ('floor-back-extension','Floor Back Extension','Back','Bodyweight'),
  ('good-morning','Good Morning','Back','Barbell'),
  ('gorilla-row','Gorilla Row','Back','Bodyweight'),
  ('hang-clean','Hang Clean','Back','Barbell'),
  ('hang-power-clean','Hang Power Clean','Back','Barbell'),
  ('hang-power-snatch','Hang Power Snatch','Back','Barbell'),
  ('hang-snatch','Hang Snatch','Back','Barbell'),
  ('inverted-row','Inverted Row','Back','Bodyweight'),
  ('inverted-row-with-underhand-grip','Inverted Row with Underhand Grip','Back','Bodyweight'),
  ('jefferson-curl','Jefferson Curl','Back','Bodyweight'),
  ('jumping-muscle-up','Jumping Muscle-Up','Back','Bodyweight'),
  ('kettlebell-clean','Kettlebell Clean','Back','Kettlebell'),
  ('kettlebell-clean-jerk','Kettlebell Clean & Jerk','Back','Kettlebell'),
  ('kettlebell-clean-press','Kettlebell Clean & Press','Back','Kettlebell'),
  ('kettlebell-row','Kettlebell Row','Back','Kettlebell'),
  ('kettlebell-snatch','Kettlebell Snatch','Back','Kettlebell'),
  ('kettlebell-swing','Kettlebell Swing','Back','Kettlebell'),
  ('kroc-row','Kroc Row','Back','Bodyweight'),
  ('lat-pulldown-with-neutral-grip','Lat Pulldown With Neutral Grip','Back','Cable'),
  ('lat-pulldown-with-pronated-grip','Lat Pulldown With Pronated Grip','Back','Cable'),
  ('lat-pulldown-with-supinated-grip','Lat Pulldown With Supinated Grip','Back','Cable'),
  ('machine-lat-pulldown','Machine Lat Pulldown','Back','Cable'),
  ('muscle-up-bar','Muscle-Up (Bar)','Back','Bodyweight'),
  ('muscle-up-rings','Muscle-Up (Rings)','Back','Gymnastic Rings'),
  ('neutral-close-grip-lat-pulldown','Neutral Close-Grip Lat Pulldown','Back','Cable'),
  ('one-handed-cable-row','One-Handed Cable Row','Back','Cable'),
  ('one-handed-kettlebell-swing','One-Handed Kettlebell Swing','Back','Kettlebell'),
  ('one-handed-lat-pulldown','One-Handed Lat Pulldown','Back','Cable'),
  ('pause-deadlift','Pause Deadlift','Back','Barbell'),
  ('pendlay-row','Pendlay Row','Back','Barbell'),
  ('power-clean','Power Clean','Back','Barbell'),
  ('power-snatch','Power Snatch','Back','Barbell'),
  ('pull-up','Pull-Up','Back','Bodyweight'),
  ('pull-up-with-a-neutral-grip','Pull-Up With a Neutral Grip','Back','Bodyweight'),
  ('rack-pull','Rack Pull','Back','Barbell'),
  ('renegade-row','Renegade Row','Back','Bodyweight'),
  ('rope-pulldown','Rope Pulldown','Back','Cable'),
  ('ring-pull-up','Ring Pull-Up','Back','Gymnastic Rings'),
  ('ring-row','Ring Row','Back','Gymnastic Rings'),
  ('scap-pull-up','Scap Pull-Up','Back','Bodyweight'),
  ('seal-row','Seal Row','Back','Barbell'),
  ('machine-row','Seated Machine Row','Back','Machine'),
  ('single-leg-deadlift-with-kettlebell','Single Leg Deadlift with Kettlebell','Back','Kettlebell'),
  ('smith-machine-deadlift','Smith Machine Deadlift','Back','Smith Machine'),
  ('smith-machine-one-handed-row','Smith Machine One-Handed Row','Back','Smith Machine'),
  ('snatch','Snatch','Back','Barbell'),
  ('snatch-grip-deadlift','Snatch Grip Deadlift','Back','Barbell'),
  ('stiff-legged-deadlift','Stiff-Legged Deadlift','Back','Barbell'),
  ('straight-arm-lat-pulldown','Straight Arm Lat Pulldown','Back','Cable'),
  ('sumo-deadlift','Sumo Deadlift','Back','Barbell'),
  ('superman-raise','Superman Raise','Back','Bodyweight'),
  ('t-bar-row','T-Bar Row','Back','Bodyweight'),
  ('towel-row','Towel Row','Back','Bodyweight'),
  ('trap-bar-deadlift-with-high-handles','Trap Bar Deadlift With High Handles','Back','Trap Bar'),
  ('trap-bar-deadlift-with-low-handles','Trap Bar Deadlift With Low Handles','Back','Trap Bar'),
  ('banded-side-kicks','Banded Side Kicks','Glutes','Resistance Band'),
  ('cable-glute-kickback','Cable Glute Kickback','Glutes','Cable'),
  ('cable-pull-through','Cable Pull Through','Glutes','Cable'),
  ('cable-machine-hip-abduction','Cable Machine Hip Abduction','Glutes','Cable'),
  ('clamshells','Clamshells','Glutes','Bodyweight'),
  ('cossack-squat','Cossack Squat','Glutes','Barbell'),
  ('death-march-with-dumbbells','Death March with Dumbbells','Glutes','Dumbbell'),
  ('donkey-kicks','Donkey Kicks','Glutes','Bodyweight'),
  ('dumbbell-romanian-deadlift','Dumbbell Romanian Deadlift','Glutes','Dumbbell'),
  ('dumbbell-frog-pumps','Dumbbell Frog Pumps','Glutes','Dumbbell'),
  ('fire-hydrants','Fire Hydrants','Glutes','Bodyweight'),
  ('frog-pumps','Frog Pumps','Glutes','Bodyweight'),
  ('glute-bridge','Glute Bridge','Glutes','Bodyweight'),
  ('hip-abduction-against-band','Hip Abduction Against Band','Glutes','Resistance Band'),
  ('machine-hip-abduction','Hip Abduction Machine','Glutes','Machine'),
  ('hip-thrust','Hip Thrust','Glutes','Bodyweight'),
  ('machine-hip-thrust','Hip Thrust Machine','Glutes','Machine'),
  ('hip-thrust-with-band-around-knees','Hip Thrust With Band Around Knees','Glutes','Resistance Band'),
  ('kettlebell-windmill','Kettlebell Windmill','Glutes','Kettlebell'),
  ('lateral-walk-with-band','Lateral Walk With Band','Glutes','Resistance Band'),
  ('machine-glute-kickbacks','Machine Glute Kickbacks','Glutes','Machine'),
  ('one-legged-glute-bridge','One-Legged Glute Bridge','Glutes','Bodyweight'),
  ('one-legged-hip-thrust','One-Legged Hip Thrust','Glutes','Bodyweight'),
  ('reverse-hyperextension','Reverse Hyperextension','Glutes','Bodyweight'),
  ('smith-machine-hip-thrust','Smith Machine Hip Thrust','Glutes','Smith Machine'),
  ('single-leg-romanian-deadlift','Single Leg Romanian Deadlift','Glutes','Barbell'),
  ('standing-hip-abduction-against-band','Standing Hip Abduction Against Band','Glutes','Resistance Band'),
  ('standing-glute-kickback-in-machine','Standing Glute Kickback in Machine','Glutes','Machine'),
  ('standing-glute-push-down','Standing Glute Push Down','Glutes','Bodyweight'),
  ('ball-slams','Ball Slams','Core','Medicine Ball'),
  ('bicycle-crunch','Bicycle Crunch','Core','Bodyweight'),
  ('cable-crunches','Cable Crunch','Core','Cable'),
  ('captains-chair-knee-raise','Captain’s Chair Knee Raise','Core','Bodyweight'),
  ('captains-chair-leg-raise','Captain’s Chair Leg Raise','Core','Bodyweight'),
  ('copenhagen-plank','Copenhagen Plank','Core','Bodyweight'),
  ('core-twist','Core Twist','Core','Bodyweight'),
  ('crunch','Crunch','Core','Bodyweight'),
  ('dead-bug','Dead Bug','Core','Bodyweight'),
  ('dead-bug-with-dumbbells','Dead Bug With Dumbbells','Core','Dumbbell'),
  ('dragon-flag','Dragon Flag','Core','Bodyweight'),
  ('hanging-knee-raise','Hanging Knee Raise','Core','Bodyweight'),
  ('hanging-leg-raise','Hanging Leg Raise','Core','Bodyweight'),
  ('hanging-sit-up','Hanging Sit-Up','Core','Bodyweight'),
  ('hollow-body-crunch','Hollow Body Crunch','Core','Bodyweight'),
  ('hollow-hold','Hollow Hold','Core','Bodyweight'),
  ('jackknife-sit-up','Jackknife Sit-Up','Core','Bodyweight'),
  ('kettlebell-plank-pull-through','Kettlebell Plank Pull Through','Core','Kettlebell'),
  ('kneeling-ab-wheel-roll-out','Kneeling Ab Wheel Roll-Out','Core','Bodyweight'),
  ('kneeling-plank','Kneeling Plank','Core','Bodyweight'),
  ('l-sit','L-Sit','Core','Bodyweight'),
  ('lying-leg-raise','Lying Leg Raise','Core','Bodyweight'),
  ('machine-crunch','Machine Crunch','Core','Machine'),
  ('mountain-climbers','Mountain Climbers','Core','Bodyweight'),
  ('pallof-press','Pallof Press','Core','Bodyweight'),
  ('plank','Plank','Core','Bodyweight'),
  ('plank-with-leg-lifts','Plank with Leg Lifts','Core','Bodyweight'),
  ('plank-with-shoulder-taps','Plank with Shoulder Taps','Core','Bodyweight'),
  ('sit-up','Sit-Up','Core','Bodyweight'),
  ('weighted-plank','Weighted Plank','Core','Bodyweight'),
  ('dynamic-side-plank','Dynamic Side Plank','Obliques','Bodyweight'),
  ('hanging-windshield-wiper','Hanging Windshield Wiper','Obliques','Bodyweight'),
  ('high-to-low-wood-chop-with-band','High to Low Wood Chop with Band','Obliques','Resistance Band'),
  ('high-to-low-wood-chop-with-cable','High to Low Wood Chop with Cable','Obliques','Cable'),
  ('horizontal-wood-chop-with-band','Horizontal Wood Chop with Band','Obliques','Resistance Band'),
  ('horizontal-wood-chop-with-cable','Horizontal Wood Chop with Cable','Obliques','Cable'),
  ('kneeling-side-plank','Kneeling Side Plank','Obliques','Bodyweight'),
  ('low-to-high-wood-chop-with-band','Low to High Wood Chop with Band','Obliques','Resistance Band'),
  ('low-to-high-wood-chop-with-cable','Low to High Wood Chop with Cable','Obliques','Cable'),
  ('lying-windshield-wiper','Lying Windshield Wiper','Obliques','Bodyweight'),
  ('lying-windshield-wiper-with-bent-knees','Lying Windshield Wiper with Bent Knees','Obliques','Bodyweight'),
  ('oblique-crunch','Oblique Crunch','Obliques','Bodyweight'),
  ('oblique-sit-up','Oblique Sit-Up','Obliques','Bodyweight'),
  ('barbell-standing-calf-raise','Barbell Standing Calf Raise','Calves','Barbell'),
  ('barbell-seated-calf-raise','Barbell Seated Calf Raise','Calves','Barbell'),
  ('calf-raise-in-leg-press','Calf Raise in Leg Press','Calves','Machine'),
  ('donkey-calf-raise','Donkey Calf Raise','Calves','Bodyweight'),
  ('eccentric-heel-drop','Eccentric Heel Drop','Calves','Bodyweight'),
  ('heel-raise','Heel Raise','Calves','Bodyweight'),
  ('seated-calf-raise','Seated Calf Raise','Calves','Bodyweight'),
  ('standing-calf-raise','Standing Calf Raise','Calves','Bodyweight'),
  ('barbell-wrist-curl-behind-the-back','Barbell Wrist Curl Behind the Back','Forearms','Barbell'),
  ('bar-hang','Bar Hang','Forearms','Bodyweight'),
  ('farmers-walk','Farmers Walk','Forearms','Dumbbell'),
  ('fat-bar-deadlift','Fat Bar Deadlift','Forearms','Barbell'),
  ('gripper','Gripper','Forearms','Other'),
  ('one-handed-bar-hang','One-Handed Bar Hang','Forearms','Bodyweight'),
  ('plate-wrist-curl','Plate Wrist Curl','Forearms','Plate'),
  ('towel-pull-up','Towel Pull-Up','Forearms','Bodyweight'),
  ('barbell-wrist-extension','Barbell Wrist Extension','Forearms','Barbell'),
  ('dumbbell-wrist-extension','Dumbbell Wrist Extension','Forearms','Dumbbell'),
  ('lying-neck-curl','Lying Neck Curl','Neck','Bodyweight'),
  ('lying-neck-extension','Lying Neck Extension','Neck','Bodyweight'),
  ('prone-neck-bridge','Prone Neck Bridge','Neck','Bodyweight'),
  ('supine-neck-bridge','Supine Neck Bridge','Neck','Bodyweight')
),
missing as (
  select catalogue.*
  from catalogue
  where not exists (
    select 1
    from public.exercises existing
    where existing.owner_id is null
      and regexp_replace(lower(existing.name), '[^a-z0-9]', '', 'g')
        = regexp_replace(lower(catalogue.name), '[^a-z0-9]', '', 'g')
  )
)
insert into public.exercises (id,owner_id,name,muscle_group,equipment)
select id,null,name,muscle_group,equipment
from missing
on conflict (id) do update set
  name=excluded.name,
  muscle_group=excluded.muscle_group,
  equipment=excluded.equipment,
  updated_at=now();
